# 4. Ensembles de Arboles de Decision

## 4.3 Random Forest

*Random Forest* es un algoritmo de ensembles de arboles de decision creado por Leo Brieman en 1995-2006
https://link.springer.com/content/pdf/10.1023/a:1010933404324.pdf

La página original es:
https://www.stat.berkeley.edu/~breiman/RandomForests/cc_home.htm

Dos buenos videos para seguir el paso a paso de Random Forest y aplicaciones:
* https://www.youtube.com/watch?v=J4Wdy0Wc_xQ
* https://www.youtube.com/watch?v=sQ870aTKqiM

Qué tipo de perturbaciones se realizan en Random Forest

*   Se perturba el dataset, con la técnica de bagging = Bootstrap Aggregating
*   Tambien se perturba el algoritmo, utiliza random en cada split

Cada arbolito de Random Forest se entrena sobre un dataset perturbado, que tiene :
* todas las columnas originales (esta es una GRAN diferencia con  Arboles Azarosos)
* la misma *cantidad* de registros del dataset original, PERO generados por la técnica de sampleo con reposición del dataset original.

A pesar de que Leo Brieman es también el inventor de CART (Classification and Regression Trees) Random Forest no corre el algoritmo CART de la libreria rpart, sino un CART perturbado, en donde cada split NO se hace sobre todos los campos del dataset, sino sobre un csubconjunto tomado al azar, esa cantidad es el hiperparámetro *mtry*

#### 4.3.1  Seteo del ambiente en Google Colab

Esta parte se debe correr con el runtime en Python3
<br>Ir al menu, Runtime -> Change Runtime Type -> Runtime type ->  **Python 3**

Conectar la virtual machine donde esta corriendo Google Colab con el  Google Drive, para poder tener persistencia de archivos

In [ ]:
# primero establecer el Runtime de Python 3
from google.colab import drive
drive.mount('/content/.drive')

Para correr la siguiente celda es fundamental en Arranque en Frio haber copiado el archivo kaggle.json al Google Drive, en la carpeta indicada en el instructivo

<br>los siguientes comando estan en shell script de Linux
*   Crear las carpetas en el Google Drive
*   "instalar" el archivo kaggle.json desde el Google Drive a la virtual machine para que pueda ser utilizado por la libreria  kaggle de Python
*   Bajar el  **dataset_pequeno**  al  Google Drive  y tambien al disco local de la virtual machine que esta corriendo Google Colab

In [ ]:
%%shell

mkdir -p "/content/.drive/My Drive/dm"
mkdir -p "/content/buckets"
ln -s "/content/.drive/My Drive/dm" /content/buckets/b1

mkdir -p ~/.kaggle
cp /content/buckets/b1/kaggle/kaggle.json  ~/.kaggle
chmod 600 ~/.kaggle/kaggle.json


mkdir -p /content/buckets/b1/exp
mkdir -p /content/buckets/b1/datasets
mkdir -p /content/datasets



archivo_origen="https://storage.googleapis.com/open-courses/itba2025-8d0a/dataset_pequeno.csv"
archivo_destino="/content/datasets/dataset_pequeno.csv"
archivo_destino_bucket="/content/buckets/b1/datasets/dataset_pequeno.csv"

if ! test -f $archivo_destino_bucket; then
  wget  $archivo_origen  -O $archivo_destino_bucket
fi


if ! test -f $archivo_destino; then
  cp  $archivo_destino_bucket  $archivo_destino
fi

### 4.4  Random Forest, una corrida

El tiempo de corrida de este punto es de alrededor de 8 minutos

Esta parte se debe correr con el runtime en lenguaje **R** Ir al menu, Runtime -> Change Runtime Type -> Runtime type -> R

limpio el ambiente de R

In [ ]:
format(Sys.time(), "%a %b %d %X %Y")

In [ ]:
# limpio la memoria
rm(list=ls(all.names=TRUE)) # remove all objects
gc(full=TRUE, verbose=FALSE) # garbage collection

**ranger** es una de las muchas librerías en lenguage R que implementa el algoritmo *Random Forest*, tiene la ventaja que corre el paralelo, utilizando todos los nucleos del procesador.

In [ ]:
# cargo las librerias que necesito
require("data.table")
require("rpart")

# ranger se usa para procesar
if( !require("ranger") ) install.packages("ranger")
require("ranger")

# randomForest  solo se usa para imputar nulos
if( !require("randomForest") ) install.packages("randomForest")
require("randomForest")

Aqui debe cargar SU semilla primigenia y

In [ ]:
PARAM <- list()
PARAM$experimento <- 440
PARAM$semilla_primigenia <- 102191

PARAM$ranger$num.trees <- 300 # cantidad de arboles
PARAM$ranger$mtry <- 13 # cantidad de atributos que participan en cada split
PARAM$ranger$min.node.size <- 50 # tamaño minimo de las hojas
PARAM$ranger$max.depth <- 10 # 0 significa profundidad infinita

In [ ]:
# carpeta de trabajo
setwd("/content/buckets/b1/exp")
experimento_folder <- paste0("KA", PARAM$experimento)
dir.create(experimento_folder, showWarnings=FALSE)
setwd( paste0("/content/buckets/b1/exp/", experimento_folder ))

In [ ]:
# lectura del dataset
dataset <- fread("/content/datasets/dataset_pequeno.csv")

In [ ]:
#  estas dos lineas estan relacionadas con el Data Drifting
# asigno un valor muy negativo

if( "Master_Finiciomora" %in% colnames(dataset) )
  dataset[ is.na(Master_Finiciomora) , Master_Finiciomora := -999 ]

if( "Visa_Finiciomora" %in% colnames(dataset) )
  dataset[ is.na(Visa_Finiciomora) , Visa_Finiciomora :=  -999 ]

In [ ]:
# defino los dataset de entrenamiento y aplicacion
dtrain <- dataset[foto_mes == 202107]
dfuture <- dataset[foto_mes == 202109]

In [ ]:
set.seed( PARAM$semilla_primigenia ) # Establezco la semilla aleatoria


# ranger necesita la clase de tipo factor
factorizado <- as.factor(dtrain$clase_ternaria)
dtrain[, clase_ternaria := factorizado]

In [ ]:
# Ranger NO acepta valores nulos
# Leo Breiman, ¿por que le temias a los nulos?
# imputo los nulos, ya que ranger no acepta nulos
dtrain <- na.roughfix(dtrain)

In [ ]:
setorder(dtrain, clase_ternaria) # primero quedan los BAJA+1, BAJA+2, CONTINUA

# genero el modelo de Random Forest llamando a ranger()
modelo <- ranger(
  formula= "clase_ternaria ~ .",
  data= dtrain,
  probability= TRUE, # para que devuelva las probabilidades
  num.trees= PARAM$ranger$num.trees,
  mtry= PARAM$ranger$mtry,
  min.node.size= PARAM$ranger$min.node.size,
  max.depth= PARAM$ranger$max.depth
)

In [ ]:
# Carpinteria necesaria sobre  dfuture
# como quiere la Estadistica Clasica, imputar nulos por separado
# ( aunque en este caso ya tengo los datos del futuro de antemano
#  pero bueno, sigamos el librito de estos fundamentalistas a rajatabla ...

dfuture[, clase_ternaria := NULL]
dfuture <- na.roughfix(dfuture)

In [ ]:
tb_prediccion <- dfuture[, list(numero_de_cliente)]

In [ ]:
# aplico el modelo a los datos que no tienen clase
# aplico el modelo recien creado a los datos del futuro
prediccion <- predict(modelo, dfuture)

tb_prediccion[, prob := prediccion$predictions[, "BAJA+2"] ]

In [ ]:
tb_prediccion[, Predicted := as.numeric(prob > (1/40))]

In [ ]:
archivo_kaggle <- paste0("KA", PARAM$experimento,".csv")

# grabo el archivo
fwrite( tb_prediccion[, list(numero_de_cliente, Predicted)],
 file= archivo_kaggle,
 sep= ","
)

In [ ]:
# subida a Kaggle
comando <- "kaggle competitions submit"
competencia <- "-c data-mining-analista-sr-2025-b"
arch <- paste( "-f", archivo_kaggle)

mensaje <- paste0("-m 'num.trees=", PARAM$ranger$num.trees, "  mtry=", PARAM$ranger$mtry, "  min.node.size=", PARAM$ranger$min.node.size, " max.depth=", PARAM$ranger$max.depth, "'" )
linea <- paste( comando, competencia, arch, mensaje)
salida <- system(linea, intern= TRUE)
cat(salida)

In [ ]:
format(Sys.time(), "%a %b %d %X %Y")



---

### 4.5  Random Forest  optimizacion de hiperparámetros

Random Forest es un algoritmo que quedó obsoleto luego de la aparición de  XGBoost y LightGBM, debido a lo lento de las librerías que lo implementan.
<br> El siguiente script se brinda simplemente a modo pedagógico, advirtiendo a los alumn@s que demanda más de 24 horas para correr, y los resultados son mediocres.

limpio el ambiente de R

In [1]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Sun Aug 31 17:27:17 2025"

In [2]:
# limpio la memoria
rm(list=ls(all.names=TRUE)) # remove all objects
gc(full=TRUE, verbose=FALSE) # garbage collection

       used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  656930 35.1 1439320    76.9 1431594  76.5
Vcells 1224903  9.4 8388608    64.0 1924969  14.7

**ranger** es una de las muchas librerías en lenguage R que implementa el algoritmo *Random Forest*, tiene la ventaja que corre el paralelo, utilizando todos los nucleos del procesador.

In [3]:
# cargo las librerias que necesito
require("data.table")
require("rpart")
require("parallel")

if( !require("primes") ) install.packages("primes")
require("primes")

if( !require("rlist") ) install.packages("rlist")
require("rlist")

# ranger se usa para procesar
if( !require("ranger") ) install.packages("ranger")
require("ranger")

# randomForest  solo se usa para imputar nulos
if( !require("randomForest") ) install.packages("randomForest")
require("randomForest")


if( !require("DiceKriging") ) install.packages("DiceKriging")
require("DiceKriging")

if( !require("mlrMBO") ) install.packages("mlrMBO")
require("mlrMBO")

Loading required package: data.table

Loading required package: rpart

Loading required package: parallel

Loading required package: primes

Loading required package: rlist

Loading required package: ranger

Loading required package: randomForest

randomForest 4.7-1.2

Type rfNews() to see new features/changes/bug fixes.


Attaching package: ‘randomForest’


The following object is masked from ‘package:ranger’:

    importance


Loading required package: DiceKriging

Loading required package: mlrMBO

Loading required package: mlr

Loading required package: ParamHelpers

Loading required package: smoof

Loading required package: checkmate


Attaching package: ‘checkmate’


The following object is masked from ‘package:DiceKriging’:

    checkNames

Aqui debe cargar SU semilla primigenia y

In [4]:
PARAM <- list()
PARAM$experimento <- 450
PARAM$semilla_primigenia <- 486589

PARAM$hyperparametertuning$iteraciones <- 100
PARAM$hyperparametertuning$xval_folds <- 5
PARAM$hyperparametertuning$POS_ganancia <- 117000
PARAM$hyperparametertuning$NEG_ganancia <- -3000

# Estructura que define los hiperparámetros y sus rangos
#  la letra L al final significa ENTERO
# max.depth 0 significa profundidad infinita
PARAM$hyperparametertuning$hs <- makeParamSet(
  makeIntegerParam("num.trees", lower= 20L, upper= 500L),
  makeIntegerParam("max.depth", lower= 1L, upper= 30L),
  makeIntegerParam("min.node.size", lower= 1L, upper= 1000L),
  makeIntegerParam("mtry", lower= 2L, upper= 50L)
)

In [5]:
# graba a un archivo los componentes de lista
# para el primer registro, escribe antes los titulos

loguear <- function(
    reg, arch= NA, folder= "./work/",
    ext= ".txt", verbose= TRUE) {

  archivo <- arch
  if (is.na(arch)) archivo <- paste0(folder, substitute(reg), ext)

  if (!file.exists(archivo)) # Escribo los titulos
    {
      linea <- paste0(
        "fecha\t",
        paste(list.names(reg), collapse= "\t"), "\n"
      )

      cat(linea, file= archivo)
    }

  linea <- paste0(
    format(Sys.time(), "%Y%m%d %H%M%S"), "\t", # la fecha y hora
    gsub(", ", "\t", toString(reg)), "\n"
  )

  cat(linea, file= archivo, append= TRUE) # grabo al archivo

  if (verbose) cat(linea) # imprimo por pantalla
}

In [6]:
# particionar agrega una columna llamada fold a un dataset
#  que consiste en una particion estratificada segun agrupa
# particionar( data=dataset, division=c(70,30),
#  agrupa=clase_ternaria, seed=semilla)   crea una particion 70, 30
# particionar( data=dataset, division=c(1,1,1,1,1),
#   agrupa=clase_ternaria, seed=semilla)   divide el dataset en 5 particiones

particionar <- function(
    data, division, agrupa= "",
    campo= "fold", start= 1, seed= NA) {

  if (!is.na(seed)) set.seed(seed)

  bloque <- unlist(mapply(function(x, y) {
    rep(y, x)
  }, division, seq(from= start, length.out= length(division))))

  data[, (campo) := sample(rep(bloque, ceiling(.N / length(bloque))))[1:.N],
    by= agrupa
  ]
}

In [7]:
# es un paso del Cross Validation
# utiliza el fold  fold_test para testear y el resto para entrenar

ranger_Simple <- function(fold_test, pdata, param) {
  # genero el modelo

  set.seed(PARAM$semillas[2])

  modelo <- ranger(
    formula= "clase_binaria ~ .",
    data= pdata[fold != fold_test],
    probability= TRUE, # para que devuelva las probabilidades
    num.trees= param$num.trees,
    mtry= param$mtry,
    min.node.size= param$min.node.size,
    max.depth= param$max.depth
  )

  prediccion <- predict(modelo, pdata[fold == fold_test])

  ganancia_testing <- pdata[
    fold == fold_test,
    sum((prediccion$predictions[, "POS"] > 1 / 40) *
      ifelse(clase_binaria == "POS",
        PARAM$hyperparametertuning$POS_ganancia,
        PARAM$hyperparametertuning$NEG_ganancia
      ))
  ]

  return(ganancia_testing)
}

In [8]:
# realiza Cross Validation, promediando las ganancias de los folds de testing

ranger_CrossValidation <- function(
    data, param,
    pcampos_buenos, qfolds, pagrupa, semilla) {

  divi <- rep(1, qfolds)
  particionar(data, divi, seed= semilla, agrupa= pagrupa)

  ganancias <- mcmapply(ranger_Simple,
    seq(qfolds), # 1 2 3 4 5
    MoreArgs= list(data, param),
    SIMPLIFY= FALSE,
    mc.cores= 1
  ) # dejar esto en  1, porque ranger ya corre en paralelo

  data[, fold := NULL] # elimino el campo fold

  # devuelvo la ganancia promedio normalizada
  ganancia_promedio <- mean(unlist(ganancias))
  ganancia_promedio_normalizada <- ganancia_promedio * qfolds

  return(ganancia_promedio_normalizada)
}

In [9]:
# esta funcion solo puede recibir los parametros que se estan optimizando
# el resto de los parametros se pasan como variables globales

EstimarGanancia_ranger <- function(x) {
  GLOBAL_iteracion <<- GLOBAL_iteracion + 1

  xval_folds <- PARAM$hyperparametertuning$xval_folds

  ganancia <- ranger_CrossValidation(dataset,
    param= x,
    qfolds= xval_folds,
    pagrupa= "clase_binaria",
    semilla= PARAM$semillas[1]
  )

  # logueo
  xx <- x
  xx$xval_folds <- xval_folds
  xx$ganancia <- ganancia
  xx$iteracion <- GLOBAL_iteracion
  loguear(xx, arch= klog)

  # si es ganancia superadora la almaceno en mejor
  if( ganancia > GLOBAL_mejor ) {
    GLOBAL_mejor <<- ganancia
    loguear(xx, arch= klog_mejor)
  }


  return(ganancia)
}

aqui se inicia el programa

In [10]:
# carpeta de trabajo
setwd("/content/buckets/b1/exp")
experimento_folder <- paste0("HT", PARAM$experimento)
dir.create(experimento_folder, showWarnings=FALSE)
setwd( paste0("/content/buckets/b1/exp/", experimento_folder ))

In [11]:
# genero numeros primos
primos <- generate_primes(min= 100000, max= 1000000)
set.seed(PARAM$semilla_primigenia) # inicializo
# me quedo con PARAM$qsemillas   semillas
PARAM$semillas <- sample(primos, 2 )

In [12]:
# lectura del dataset
dataset <- fread("/content/datasets/dataset_pequeno.csv", stringsAsFactors= TRUE)

In [13]:
dataset <- dataset[foto_mes %in% c(202107)]

In [14]:
#  estas dos lineas estan relacionadas con el Data Drifting
# asigno un valor muy negativo

if( "Master_Finiciomora" %in% colnames(dataset) )
  dataset[ is.na(Master_Finiciomora) , Master_Finiciomora := -999 ]

if( "Visa_Finiciomora" %in% colnames(dataset) )
  dataset[ is.na(Visa_Finiciomora) , Visa_Finiciomora :=  -999 ]

In [15]:
set.seed( PARAM$semilla_primigenia ) # Establezco la semilla aleatoria

In [16]:
# en estos archivos quedan los resultados
kbayesiana <- paste0("HT", PARAM$experimento, ".RDATA")
klog <- paste0("HT", PARAM$experimento, ".txt")
klog_mejor <- paste0("HT", PARAM$experimento, "_mejor.txt")

GLOBAL_iteracion <- 0 # inicializo la variable global
GLOBAL_mejor <- -Inf

# si ya existe el archivo log, traigo hasta donde llegue
if (file.exists(klog)) {
  tabla_log <- fread(klog)
  GLOBAL_iteracion <- nrow(tabla_log)
}

In [17]:
# paso a trabajar con clase binaria POS={BAJA+2}   NEG={BAJA+1, CONTINUA}
dataset[, clase_binaria :=
  as.factor(ifelse(clase_ternaria == "BAJA+2", "POS", "NEG"))]

dataset[, clase_ternaria := NULL] # elimino la clase_ternaria, ya no la necesito

In [18]:
# Ranger NO acepta valores nulos
# Leo Breiman, ¿por que le temias a los nulos?
# imputo los nulos, ya que ranger no acepta nulos

dataset <- na.roughfix(dataset)

In [19]:
# Aqui comienza la configuracion de la Bayesian Optimization

configureMlr(show.learner.output = FALSE)

funcion_optimizar <- EstimarGanancia_ranger

# configuro la busqueda bayesiana,  los hiperparametros que se van a optimizar
# por favor, no desesperarse por lo complejo
obj.fun <- makeSingleObjectiveFunction(
  fn= funcion_optimizar,
  minimize= FALSE, # estoy Maximizando la ganancia
  noisy= TRUE,
  par.set= PARAM$hyperparametertuning$hs,
  has.simple.signature= FALSE
)

ctrl <- makeMBOControl(save.on.disk.at.time= 600, save.file.path= kbayesiana)

ctrl <- setMBOControlTermination(
  ctrl,
  iters= PARAM$hyperparametertuning$iteraciones
)

ctrl <- setMBOControlInfill(ctrl, crit= makeMBOInfillCritEI())

surr.km <- makeLearner(
  "regr.km",
  predict.type= "se",
  covtype= "matern3_2",
  control= list(trace= TRUE)
)

In [20]:
# inicio la optimizacion bayesiana

if (!file.exists(kbayesiana)) {
  run <- mbo(obj.fun, learner= surr.km, control= ctrl)
} else {
  run <- mboContinue(kbayesiana)
} # retomo en caso que ya exista

Computing y column(s) for design. Not provided.

Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 1 minute, 24 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 29 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 2 minutes, 53 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 2 minutes, 22 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 38 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 29 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 2 minutes, 59 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 24 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 38 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 26 seconds.
20250831 174743	169	18	661	33	5	54585000	1
20250831 174745	169	18	661	33	5	54585000	1
Growing trees.. Progress: 22%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 1 minute, 54 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 1 minute, 54 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 14 seconds.
20250831 175839	239	8	565	30	5	55035000	2
20250831 175840	239	8	565	30	5	55035000	2
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 1 minute, 52 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 51 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 5 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 1 minute, 24 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 1 minute, 52 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 20 seconds.
20250831 181700	398	21	367	15	5	54846000	3
Growing trees.. Progress: 5%. Estimated remaining time: 11 minutes, 7 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 46 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 57 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 9 minutes, 30 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 8 minutes, 54 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 8 minutes, 28 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 7 minutes, 51 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 7 minutes, 22 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 6 minutes, 49 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 6 minutes, 16 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 5 minutes, 45 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 5 minutes, 12 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 4 minutes, 38 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 4 minutes, 7 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 3 minutes, 32 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 8 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 37 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 6 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 9 minutes, 40 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 9 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 8 minutes, 28 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 7 minutes, 57 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 7 minutes, 27 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 6 minutes, 51 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 6 minutes, 20 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 5 minutes, 46 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 5 minutes, 13 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 4 minutes, 43 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 4 minutes, 12 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 3 minutes, 38 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 3 minutes, 8 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 11 minutes, 7 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 46 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 10 minutes, 17 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 9 minutes, 47 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 20 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 8 minutes, 37 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 8 minutes, 13 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 7 minutes, 40 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 7 minutes, 10 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 6 minutes, 37 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 6 minutes, 1 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 5 minutes, 32 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 4 minutes, 59 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 28 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 53 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 18 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 47 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 8 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 47 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 19 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 9 minutes, 42 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 16 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 8 minutes, 42 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 8 minutes, 11 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 7 minutes, 33 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 7 minutes, 0 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 6 minutes, 28 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 5 minutes, 53 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 5 minutes, 22 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 4 minutes, 49 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 18 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 3 minutes, 44 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 55 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 11 minutes, 0 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 28 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 10 minutes, 42 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 10 minutes, 31 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 10 minutes, 23 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 10 minutes, 6 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 9 minutes, 49 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 9 minutes, 20 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 9 minutes, 3 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 8 minutes, 41 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 8 minutes, 10 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 7 minutes, 42 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 7 minutes, 15 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 6 minutes, 48 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 6 minutes, 20 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 5 minutes, 48 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 5 minutes, 15 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 4 minutes, 50 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 4 minutes, 21 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 3 minutes, 48 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 3 minutes, 19 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 50 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 20 seconds.
20250831 192023	361	24	90	49	5	51114000	4
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 34 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 4 minutes, 54 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 4 minutes, 15 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 53 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 3 minutes, 20 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 51 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 50 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 3 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 30 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 3 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 29 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 2 minutes, 57 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 54 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 8 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 2 minutes, 32 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 24 seconds.
20250831 194430	495	15	512	18	5	55458000	5
20250831 194431	495	15	512	18	5	55458000	5
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 49 seconds.

[mbo] 0: num.trees=169; max.depth=18; min.node.size=661; mtry=33 : y = 5.46e+07 : 1199.8 secs : initdesign

[mbo] 0: num.trees=239; max.depth=8; min.node.size=565; mtry=30 : y = 5.5e+07 : 655.0 secs : initdesign

[mbo] 0: num.trees=398; max.depth=21; min.node.size=367; mtry=15 : y = 5.48e+07 : 1100.7 secs : initdesign

[mbo] 0: num.trees=361; max.depth=24; min.node.size=90; mtry=49 : y = 5.11e+07 : 3803.0 secs : initdesign

[mbo] 0: num.trees=495; max.depth=15; min.node.size=512; mtry=18 : y = 5.55e+07 : 1447.1 secs : initdesign

[mbo] 0: num.trees=271; max.depth=12; min.node.size=176; mtry=25 : y = 5.62e+07 : 907.7 secs : initdesign

[mbo] 0: num.trees=43; max.depth=6; min.node.size=777; mtry=21 : y = 5.24e+07 : 63.5 secs : initdesign

[mbo] 0: num.trees=219; max.depth=21; min.node.size=734; mtry=42 : y = 5.26e+07 : 1710.4 secs : initdesign

[mbo] 0: num.trees=315; max.depth=11; min.node.size=840; mtry=11 : y = 5.54e+07 : 453.5 secs : initdesign

[mbo] 0: num.trees=326; max.depth=4; min.node.size=404; mtry=38 : y = 5.26e+07 : 396.9 secs : initdesign

[mbo] 0: num.trees=137; max.depth=27; min.node.size=56; mtry=40 : y = 4.75e+07 : 1153.9 secs : initdesign

[mbo] 0: num.trees=189; max.depth=17; min.node.size=239; mtry=5 : y = 5.53e+07 : 212.8 secs : initdesign

[mbo] 0: num.trees=447; max.depth=1; min.node.size=300; mtry=9 : y = 2.98e+07 : 50.1 secs : initdesign

[mbo] 0: num.trees=53; max.depth=29; min.node.size=903; mtry=4 : y = 5.45e+07 : 58.3 secs : initdesign

[mbo] 0: num.trees=101; max.depth=8; min.node.size=980; mtry=47 : y = 5.35e+07 : 365.5 secs : initdesign

[mbo] 0: num.trees=432; max.depth=26; min.node.size=469; mtry=27 : y = 5.41e+07 : 2227.0 secs : initdesign

Saved the current state after iteration 1 in the file HT450.RDATA.

Growing trees.. Progress: 96%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 1 seconds.
20250831 215414	69	14	1000	16	5	53310000	17

[mbo] 1: num.trees=69; max.depth=14; min.node.size=1000; mtry=16 : y = 5.33e+07 : 180.5 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 720 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 648 points instead of 1000!”

Growing trees.. Progress: 63%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 18 seconds.
20250831 215935	500	25	1000	2	5	53286000	18

[mbo] 2: num.trees=500; max.depth=25; min.node.size=1000; mtry=2 : y = 5.33e+07 : 319.8 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 895 points instead of 1000!”

Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 33 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 1 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 24 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 5 minutes, 47 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 5 minutes, 15 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 4 minutes, 38 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 4 minutes, 5 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 33 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 3 minutes, 1 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 18 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 40 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 6 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 5 minutes, 37 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 5 minutes, 4 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 4 minutes, 34 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 4 minutes, 3 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 4 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 40 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 6 minutes, 2 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 5 minutes, 34 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 5 minutes, 2 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 4 minutes, 29 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 3 minutes, 56 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 50 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 51 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 33 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 6 minutes, 6 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 5 minutes, 36 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 5 minutes, 3 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 4 minutes, 31 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 3 minutes, 57 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 26 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 4 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 40 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 16 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 5 minutes, 44 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 5 minutes, 13 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 4 minutes, 42 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 4 minutes, 10 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 3 minutes, 5 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 32 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 25 seconds.
20250831 223854	500	12	586	37	5	55647000	19

[mbo] 3: num.trees=500; max.depth=12; min.node.size=586; mtry=37 : y = 5.56e+07 : 2358.3 secs : infill_ei

Saved the current state after iteration 4 in the file HT450.RDATA.

Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 22 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 42 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 7 minutes, 14 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 6 minutes, 42 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 6 minutes, 7 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 5 minutes, 34 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 5 minutes, 3 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 4 minutes, 33 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 4 minutes, 0 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 28 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 57 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 19 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 46 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 7 minutes, 8 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 6 minutes, 34 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 6 minutes, 4 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 5 minutes, 30 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 4 minutes, 56 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 4 minutes, 24 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 51 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 3 minutes, 19 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 46 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 22 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 7 minutes, 42 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 7 minutes, 25 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 6 minutes, 52 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 6 minutes, 17 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 5 minutes, 51 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 5 minutes, 27 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 5 minutes, 1 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 4 minutes, 36 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 4 minutes, 10 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 3 minutes, 38 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 8 minutes, 22 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 1 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 7 minutes, 31 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 7 minutes, 1 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 6 minutes, 29 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 5 minutes, 59 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 5 minutes, 26 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 4 minutes, 57 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 4 minutes, 22 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 3 minutes, 51 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 3 minutes, 17 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 11 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 48 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 57 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 8 minutes, 55 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 8 minutes, 16 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 7 minutes, 38 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 6 minutes, 54 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 6 minutes, 14 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 5 minutes, 36 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 4 minutes, 59 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 4 minutes, 20 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 11 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 2 minutes, 37 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 22 seconds.
20250831 232536	482	17	1	31	5	51681000	20

[mbo] 4: num.trees=482; max.depth=17; min.node.size=1; mtry=31 : y = 5.17e+07 : 2796.9 secs : infill_ei

Saved the current state after iteration 5 in the file HT450.RDATA.

Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 50 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 50 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 53 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 1 minute, 47 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 53 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 2 minutes, 22 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 15 seconds.
20250831 234320	324	12	630	24	5	55539000	21

[mbo] 5: num.trees=324; max.depth=12; min.node.size=630; mtry=24 : y = 5.55e+07 : 1059.5 secs : infill_ei

Saved the current state after iteration 6 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 985 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 855 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 907 points instead of 1000!”

Growing trees.. Progress: 28%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 15 seconds.
20250831 235304	206	6	1	50	5	53640000	22

[mbo] 6: num.trees=206; max.depth=6; min.node.size=1; mtry=50 : y = 5.36e+07 : 580.8 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 990 points instead of 1000!”

Growing trees.. Progress: 76%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 11 seconds.
20250831 235737	500	13	226	2	5	53040000	23

[mbo] 7: num.trees=500; max.depth=13; min.node.size=226; mtry=2 : y = 5.3e+07 : 272.3 secs : infill_ei

Saved the current state after iteration 8 in the file HT450.RDATA.

Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 38 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 4 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 2 minutes, 34 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 50 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 14 seconds.
20250901 001353	208	11	255	37	5	54903000	24

[mbo] 8: num.trees=208; max.depth=11; min.node.size=255; mtry=37 : y = 5.49e+07 : 972.3 secs : infill_ei

Saved the current state after iteration 9 in the file HT450.RDATA.

Growing trees.. Progress: 38%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 20 seconds.
20250901 002119	209	19	885	12	5	55398000	25

[mbo] 9: num.trees=209; max.depth=19; min.node.size=885; mtry=12 : y = 5.54e+07 : 442.9 secs : infill_ei

Growing trees.. Progress: 49%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 0 seconds.
20250901 002707	173	11	1	15	5	54597000	26

[mbo] 10: num.trees=173; max.depth=11; min.node.size=1; mtry=15 : y = 5.46e+07 : 348.2 secs : infill_ei

Saved the current state after iteration 11 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 510 points instead of 1000!”

Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 3 minutes, 10 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 2 minutes, 41 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 2 minutes, 11 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 2 minutes, 39 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 3 minutes, 10 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 2 minutes, 38 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 3 minutes, 6 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 3 minutes, 10 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 2 minutes, 38 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 2 seconds.
20250901 004858	500	7	989	41	5	53079000	27

[mbo] 11: num.trees=500; max.depth=7; min.node.size=989; mtry=41 : y = 5.31e+07 : 1304.2 secs : infill_ei

Saved the current state after iteration 12 in the file HT450.RDATA.

20250901 004953	20	24	550	11	5	52449000	28

[mbo] 12: num.trees=20; max.depth=24; min.node.size=550; mtry=11 : y = 5.24e+07 : 51.1 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 894 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 961 points instead of 1000!”

Growing trees.. Progress: 13%. Estimated remaining time: 3 minutes, 20 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 2 minutes, 16 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 12 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 2 minutes, 43 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 2 minutes, 13 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 1 minute, 54 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 3 minutes, 23 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 19 seconds.
20250901 011059	500	30	1000	14	5	55752000	29

[mbo] 13: num.trees=500; max.depth=30; min.node.size=1000; mtry=14 : y = 5.58e+07 : 1266.6 secs : infill_ei

Saved the current state after iteration 14 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 756 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 838 points instead of 1000!”

Growing trees.. Progress: 54%. Estimated remaining time: 26 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 23 seconds.
20250901 011652	500	30	400	2	5	54063000	30

[mbo] 14: num.trees=500; max.depth=30; min.node.size=400; mtry=2 : y = 5.41e+07 : 346.4 secs : infill_ei

Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 4 minutes, 21 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 3 minutes, 48 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 3 minutes, 15 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 2 minutes, 13 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 51 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 4 minutes, 17 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 3 minutes, 17 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 2 minutes, 46 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 2 minutes, 17 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 2 minutes, 34 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 2 minutes, 42 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 2 minutes, 11 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 11 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 2 minutes, 43 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 8 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 5 seconds.
20250901 014426	500	11	221	27	5	55260000	31

[mbo] 15: num.trees=500; max.depth=11; min.node.size=221; mtry=27 : y = 5.53e+07 : 1653.8 secs : infill_ei

Saved the current state after iteration 16 in the file HT450.RDATA.

Growing trees.. Progress: 30%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 12 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 11 seconds.
20250901 015355	272	16	513	12	5	55242000	32

[mbo] 16: num.trees=272; max.depth=16; min.node.size=513; mtry=12 : y = 5.52e+07 : 565.7 secs : infill_ei

Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 25 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 51 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 3 minutes, 18 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 53 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 54 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 22 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 3 minutes, 11 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 2 minutes, 39 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 51 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 3 minutes, 24 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 53 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 23 seconds.
20250901 021758	492	28	1000	16	5	54861000	33

[mbo] 17: num.trees=492; max.depth=28; min.node.size=1000; mtry=16 : y = 5.49e+07 : 1441.8 secs : infill_ei

Saved the current state after iteration 18 in the file HT450.RDATA.

Growing trees.. Progress: 29%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 12 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 9 seconds.
20250901 022744	500	18	855	6	5	54957000	34

[mbo] 18: num.trees=500; max.depth=18; min.node.size=855; mtry=6 : y = 5.5e+07 : 583.0 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 999 points instead of 1000!”

Growing trees.. Progress: 5%. Estimated remaining time: 11 minutes, 24 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 36 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 10 minutes, 12 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 9 minutes, 36 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 9 minutes, 11 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 8 minutes, 36 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 8 minutes, 0 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 7 minutes, 28 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 6 minutes, 54 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 6 minutes, 23 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 5 minutes, 50 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 5 minutes, 19 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 4 minutes, 47 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 3 minutes, 14 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 43 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 12 minutes, 32 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 11 minutes, 30 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 49 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 10 minutes, 12 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 37 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 9 minutes, 6 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 8 minutes, 32 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 7 minutes, 59 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 7 minutes, 26 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 6 minutes, 51 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 6 minutes, 18 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 5 minutes, 46 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 5 minutes, 13 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 4 minutes, 41 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 4 minutes, 6 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 47 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 42 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 29 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 9 minutes, 53 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 26 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 8 minutes, 55 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 8 minutes, 21 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 7 minutes, 52 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 7 minutes, 18 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 6 minutes, 46 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 6 minutes, 13 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 5 minutes, 42 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 5 minutes, 10 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 4 minutes, 38 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 4 minutes, 6 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 32 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 24 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 11 minutes, 24 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 47 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 13 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 9 minutes, 46 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 10 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 8 minutes, 36 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 8 minutes, 5 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 7 minutes, 35 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 7 minutes, 5 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 6 minutes, 33 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 6 minutes, 2 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 5 minutes, 31 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 4 minutes, 59 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 4 minutes, 28 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 53 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 20 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 48 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 16 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 11 minutes, 3 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 41 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 55 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 9 minutes, 32 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 8 minutes, 55 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 8 minutes, 26 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 7 minutes, 49 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 7 minutes, 17 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 6 minutes, 43 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 6 minutes, 13 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 5 minutes, 39 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 5 minutes, 9 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 4 minutes, 35 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 59 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 24 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 22 seconds.
20250901 032813	500	14	534	50	5	55842000	35

[mbo] 19: num.trees=500; max.depth=14; min.node.size=534; mtry=50 : y = 5.58e+07 : 3629.6 secs : infill_ei

Saved the current state after iteration 20 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 998 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 480 points instead of 1000!”

Growing trees.. Progress: 3%. Estimated remaining time: 15 minutes, 37 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 14 minutes, 50 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 14 minutes, 5 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 13 minutes, 47 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 13 minutes, 10 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 12 minutes, 33 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 12 minutes, 6 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 11 minutes, 33 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 10 minutes, 59 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 10 minutes, 28 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 9 minutes, 55 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 9 minutes, 22 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 8 minutes, 51 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 8 minutes, 19 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 7 minutes, 49 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 7 minutes, 14 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 6 minutes, 39 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 6 minutes, 5 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 5 minutes, 35 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 5 minutes, 1 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 4 minutes, 25 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 3 minutes, 53 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 3 minutes, 20 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 2 minutes, 48 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 1 minute, 8 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 15 minutes, 9 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 14 minutes, 23 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 13 minutes, 47 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 13 minutes, 33 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 12 minutes, 59 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 12 minutes, 23 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 11 minutes, 52 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 11 minutes, 27 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 10 minutes, 53 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 10 minutes, 19 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 9 minutes, 47 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 9 minutes, 15 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 8 minutes, 40 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 8 minutes, 9 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 7 minutes, 41 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 7 minutes, 6 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 6 minutes, 31 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 5 minutes, 59 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 5 minutes, 28 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 4 minutes, 55 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 4 minutes, 24 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 3 minutes, 50 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 3 minutes, 20 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 2 minutes, 46 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 16 minutes, 42 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 15 minutes, 36 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 14 minutes, 52 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 14 minutes, 8 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 13 minutes, 40 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 13 minutes, 11 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 12 minutes, 29 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 12 minutes, 5 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 11 minutes, 38 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 11 minutes, 5 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 10 minutes, 27 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 9 minutes, 57 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 9 minutes, 26 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 8 minutes, 54 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 8 minutes, 20 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 7 minutes, 49 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 7 minutes, 19 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 6 minutes, 47 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 6 minutes, 13 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 5 minutes, 42 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 5 minutes, 10 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 4 minutes, 5 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 15 minutes, 37 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 14 minutes, 50 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 14 minutes, 3 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 13 minutes, 30 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 12 minutes, 53 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 12 minutes, 22 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 11 minutes, 54 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 11 minutes, 22 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 10 minutes, 53 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 10 minutes, 23 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 9 minutes, 49 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 9 minutes, 15 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 8 minutes, 44 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 8 minutes, 12 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 7 minutes, 37 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 7 minutes, 7 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 6 minutes, 32 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 5 minutes, 57 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 5 minutes, 23 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 4 minutes, 51 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 4 minutes, 18 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 3 minutes, 46 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 3 minutes, 14 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 2 minutes, 42 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 15 minutes, 37 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 15 minutes, 21 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 14 minutes, 54 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 14 minutes, 25 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 13 minutes, 54 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 13 minutes, 19 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 12 minutes, 45 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 12 minutes, 15 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 11 minutes, 35 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 11 minutes, 9 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 10 minutes, 35 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 10 minutes, 0 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 9 minutes, 27 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 8 minutes, 53 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 8 minutes, 18 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 7 minutes, 47 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 7 minutes, 14 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 6 minutes, 39 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 6 minutes, 6 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 5 minutes, 33 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 5 minutes, 2 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 4 minutes, 31 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 4 minutes, 0 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 3 minutes, 26 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 2 minutes, 53 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 7 seconds.
20250901 044940	500	30	1000	50	5	53733000	36

[mbo] 20: num.trees=500; max.depth=30; min.node.size=1000; mtry=50 : y = 5.37e+07 : 4882.8 secs : infill_ei

Saved the current state after iteration 21 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 893 points instead of 1000!”

Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 54 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 14 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 5 minutes, 40 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 5 minutes, 8 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 4 minutes, 36 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 7 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 32 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 5 minutes, 55 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 5 minutes, 20 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 4 minutes, 50 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 4 minutes, 22 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 3 minutes, 50 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 17 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 36 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 7 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 20 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 5 minutes, 51 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 5 minutes, 15 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 4 minutes, 12 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 3 minutes, 42 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 10 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 7 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 20 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 5 minutes, 47 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 5 minutes, 18 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 4 minutes, 17 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 43 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 20 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 32 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 5 minutes, 58 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 5 minutes, 25 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 4 minutes, 54 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 4 minutes, 21 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 3 minutes, 47 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 36 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 3 seconds.
20250901 052746	359	12	1	50	5	54240000	37

[mbo] 21: num.trees=359; max.depth=12; min.node.size=1; mtry=50 : y = 5.42e+07 : 2279.4 secs : infill_ei

Saved the current state after iteration 22 in the file HT450.RDATA.

20250901 052928	145	19	498	2	5	52347000	38

[mbo] 22: num.trees=145; max.depth=19; min.node.size=498; mtry=2 : y = 5.23e+07 : 98.6 secs : infill_ei

Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 51 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 20 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 5 minutes, 48 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 5 minutes, 14 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 4 minutes, 48 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 4 minutes, 21 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 3 minutes, 58 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 32 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 24 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 5 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 40 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 6 minutes, 6 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 5 minutes, 32 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 4 minutes, 57 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 4 minutes, 28 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 3 minutes, 55 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 48 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 51 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 33 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 11 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 5 minutes, 34 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 5 minutes, 2 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 4 minutes, 30 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 3 minutes, 55 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 48 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 18 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 27 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 56 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 5 minutes, 29 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 4 minutes, 56 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 4 minutes, 33 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 4 minutes, 6 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 3 minutes, 5 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 49 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 1 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 15 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 5 minutes, 37 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 5 minutes, 6 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 4 minutes, 38 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 4 minutes, 7 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 6 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 34 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 27 seconds.
20250901 060809	500	9	463	50	5	54936000	39

[mbo] 23: num.trees=500; max.depth=9; min.node.size=463; mtry=50 : y = 5.49e+07 : 2320.6 secs : infill_ei

Saved the current state after iteration 24 in the file HT450.RDATA.

Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 18 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 0 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 20 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 5 minutes, 57 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 5 minutes, 26 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 53 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 4 minutes, 19 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 9 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 24 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 4 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 26 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 5 minutes, 53 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 5 minutes, 23 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 4 minutes, 48 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 3 minutes, 42 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 39 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 4 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 26 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 5 minutes, 57 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 5 minutes, 26 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 4 minutes, 56 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 4 minutes, 25 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 3 minutes, 53 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 48 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 4 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 40 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 10 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 5 minutes, 37 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 5 minutes, 4 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 4 minutes, 29 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 3 minutes, 59 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 26 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 57 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 25 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 5 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 39 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 6 minutes, 1 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 5 minutes, 26 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 4 minutes, 56 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 4 minutes, 22 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 3 minutes, 49 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 3 minutes, 16 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 13 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 9 seconds.
20250901 064720	500	18	912	26	5	54819000	40

[mbo] 24: num.trees=500; max.depth=18; min.node.size=912; mtry=26 : y = 5.48e+07 : 2345.5 secs : infill_ei

Saved the current state after iteration 25 in the file HT450.RDATA.

Growing trees.. Progress: 22%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 25 seconds.
20250901 070041	317	30	790	13	5	55425000	41

[mbo] 25: num.trees=317; max.depth=30; min.node.size=790; mtry=13 : y = 5.54e+07 : 797.6 secs : infill_ei

Saved the current state after iteration 26 in the file HT450.RDATA.

Growing trees.. Progress: 19%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 2 minutes, 11 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 2 seconds.
20250901 071444	272	14	210	18	5	54009000	42

[mbo] 26: num.trees=272; max.depth=14; min.node.size=210; mtry=18 : y = 5.4e+07 : 836.5 secs : infill_ei

Saved the current state after iteration 27 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 953 points instead of 1000!”

Growing trees.. Progress: 45%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 36 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 6 seconds.
20250901 072054	177	17	1000	11	5	57267000	43
20250901 072055	177	17	1000	11	5	57267000	43

[mbo] 27: num.trees=177; max.depth=17; min.node.size=1000; mtry=11 : y = 5.73e+07 : 368.0 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 889 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 939 points instead of 1000!”

Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 16 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 42 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 3 minutes, 10 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 4 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 1 minute, 33 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 10 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 35 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 24 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 56 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 56 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 22 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 56 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 28 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 22 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 50 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 16 seconds.
20250901 074450	500	22	1000	16	5	55119000	44

[mbo] 28: num.trees=500; max.depth=22; min.node.size=1000; mtry=16 : y = 5.51e+07 : 1434.5 secs : infill_ei

Saved the current state after iteration 29 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 600 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 920 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 462 points instead of 1000!”

20250901 074606	20	17	1000	17	5	51777000	45

[mbo] 29: num.trees=20; max.depth=17; min.node.size=1000; mtry=17 : y = 5.18e+07 : 70.5 secs : infill_ei

Growing trees.. Progress: 61%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 21 seconds.
20250901 075119	406	30	1000	3	5	54057000	46

[mbo] 30: num.trees=406; max.depth=30; min.node.size=1000; mtry=3 : y = 5.41e+07 : 311.9 secs : infill_ei

Growing trees.. Progress: 97%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 1 seconds.
20250901 075429	189	12	1000	6	5	54330000	47

[mbo] 31: num.trees=189; max.depth=12; min.node.size=1000; mtry=6 : y = 5.43e+07 : 189.6 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 958 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 500 points instead of 1000!”

Growing trees.. Progress: 19%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 22 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 1 minute, 48 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 22 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 1 minute, 50 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 18 seconds.
20250901 080959	488	16	1000	11	5	55938000	48

[mbo] 32: num.trees=488; max.depth=16; min.node.size=1000; mtry=11 : y = 5.59e+07 : 929.0 secs : infill_ei

Saved the current state after iteration 33 in the file HT450.RDATA.

Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 1 minute, 47 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 48 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 13 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 36 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 1 seconds.
20250901 082640	309	7	1000	50	5	53604000	49

[mbo] 33: num.trees=309; max.depth=7; min.node.size=1000; mtry=50 : y = 5.36e+07 : 995.7 secs : infill_ei

Saved the current state after iteration 34 in the file HT450.RDATA.

Growing trees.. Progress: 30%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 12 seconds.
20250901 083608	222	17	1000	15	5	55440000	50

[mbo] 34: num.trees=222; max.depth=17; min.node.size=1000; mtry=15 : y = 5.54e+07 : 561.8 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 972 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 999 points instead of 1000!”

Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 9 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 12 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 47 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 11 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 2 minutes, 16 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 9 seconds.
20250901 085335	500	25	32	10	5	52512000	51

[mbo] 35: num.trees=500; max.depth=25; min.node.size=32; mtry=10 : y = 5.25e+07 : 1045.4 secs : infill_ei

Saved the current state after iteration 36 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 660 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 294 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 896 points instead of 1000!”

Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 33 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 6 minutes, 54 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 20 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 5 minutes, 48 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 5 minutes, 21 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 50 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 4 minutes, 20 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 3 minutes, 47 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 3 minutes, 15 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 42 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 36 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 49 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 6 minutes, 54 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 21 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 5 minutes, 52 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 5 minutes, 26 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 50 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 4 minutes, 17 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 3 minutes, 44 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 41 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 7 minutes, 49 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 7 minutes, 17 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 6 minutes, 45 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 6 minutes, 14 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 5 minutes, 48 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 5 minutes, 15 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 4 minutes, 40 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 4 minutes, 6 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 3 minutes, 35 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 3 minutes, 1 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 24 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 18 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 6 minutes, 47 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 12 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 5 minutes, 45 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 5 minutes, 13 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 4 minutes, 42 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 4 minutes, 12 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 37 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 4 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 40 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 6 minutes, 10 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 5 minutes, 43 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 5 minutes, 11 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 4 minutes, 8 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 3 minutes, 5 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 26 seconds.
20250901 093437	500	30	990	26	5	54870000	52

[mbo] 36: num.trees=500; max.depth=30; min.node.size=990; mtry=26 : y = 5.49e+07 : 2458.4 secs : infill_ei

Saved the current state after iteration 37 in the file HT450.RDATA.

Growing trees.. Progress: 55%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 24 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 25 seconds.
20250901 093950	194	17	1000	9	5	55035000	53

[mbo] 37: num.trees=194; max.depth=17; min.node.size=1000; mtry=9 : y = 5.5e+07 : 308.9 secs : infill_ei

Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 14 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 2 minutes, 42 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 2 minutes, 9 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 14 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 2 minutes, 9 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 2 minutes, 37 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 14 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 2 minutes, 37 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 14 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 2 minutes, 39 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 28 seconds.
20250901 095839	269	11	830	37	5	54291000	54

[mbo] 38: num.trees=269; max.depth=11; min.node.size=830; mtry=37 : y = 5.43e+07 : 1129.5 secs : infill_ei

Saved the current state after iteration 39 in the file HT450.RDATA.

20250901 100158	304	20	951	2	5	53532000	55

[mbo] 39: num.trees=304; max.depth=20; min.node.size=951; mtry=2 : y = 5.35e+07 : 193.6 secs : infill_ei

Growing trees.. Progress: 38%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 19 seconds.
20250901 100917	289	9	1	14	5	54375000	56

[mbo] 40: num.trees=289; max.depth=9; min.node.size=1; mtry=14 : y = 5.44e+07 : 438.3 secs : infill_ei

Saved the current state after iteration 41 in the file HT450.RDATA.

Growing trees.. Progress: 86%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 5 seconds.
20250901 101256	243	11	62	5	5	53784000	57

[mbo] 41: num.trees=243; max.depth=11; min.node.size=62; mtry=5 : y = 5.38e+07 : 215.4 secs : infill_ei

20250901 101601	266	30	893	2	5	52572000	58

[mbo] 42: num.trees=266; max.depth=30; min.node.size=893; mtry=2 : y = 5.26e+07 : 184.1 secs : infill_ei

Growing trees.. Progress: 26%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 1 minute, 24 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 27 seconds.
20250901 102645	370	16	999	10	5	55122000	59

[mbo] 43: num.trees=370; max.depth=16; min.node.size=999; mtry=10 : y = 5.51e+07 : 642.9 secs : infill_ei

Saved the current state after iteration 44 in the file HT450.RDATA.

Growing trees.. Progress: 47%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 9 seconds.
20250901 103313	172	16	818	12	5	54417000	60

[mbo] 44: num.trees=172; max.depth=16; min.node.size=818; mtry=12 : y = 5.44e+07 : 384.4 secs : infill_ei

Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 37 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 28 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 1 minute, 31 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 28 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 39 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 30 seconds.
20250901 104940	499	11	982	15	5	54405000	61

[mbo] 45: num.trees=499; max.depth=11; min.node.size=982; mtry=15 : y = 5.44e+07 : 985.7 secs : infill_ei

Saved the current state after iteration 46 in the file HT450.RDATA.

Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 57 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 11 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 41 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 10 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 1 minute, 52 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 1 minute, 52 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 15 seconds.
20250901 110731	477	17	126	11	5	56127000	62

[mbo] 46: num.trees=477; max.depth=17; min.node.size=126; mtry=11 : y = 5.61e+07 : 1067.1 secs : infill_ei

Saved the current state after iteration 47 in the file HT450.RDATA.

Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 47 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 11 minutes, 9 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 24 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 9 minutes, 46 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 20 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 8 minutes, 52 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 8 minutes, 23 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 7 minutes, 53 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 7 minutes, 21 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 6 minutes, 48 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 6 minutes, 20 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 5 minutes, 48 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 5 minutes, 24 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 4 minutes, 51 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 4 minutes, 23 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 3 minutes, 50 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 37 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 18 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 47 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 47 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 10 minutes, 3 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 9 minutes, 26 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 8 minutes, 45 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 8 minutes, 8 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 7 minutes, 34 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 7 minutes, 3 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 6 minutes, 31 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 5 minutes, 59 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 5 minutes, 26 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 4 minutes, 55 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 4 minutes, 23 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 3 minutes, 51 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 3 minutes, 20 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 2 minutes, 51 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 47 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 42 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 9 minutes, 57 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 37 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 8 minutes, 59 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 28 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 7 minutes, 56 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 7 minutes, 22 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 6 minutes, 53 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 6 minutes, 22 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 5 minutes, 50 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 5 minutes, 18 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 41 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 11 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 14 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 53 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 34 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 9 minutes, 15 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 8 minutes, 52 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 8 minutes, 21 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 7 minutes, 43 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 7 minutes, 10 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 6 minutes, 35 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 6 minutes, 3 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 5 minutes, 29 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 4 minutes, 56 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 4 minutes, 22 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 3 minutes, 52 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 19 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 46 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 13 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 42 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 16 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 40 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 9 minutes, 9 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 35 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 8 minutes, 4 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 7 minutes, 30 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 6 minutes, 57 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 6 minutes, 26 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 5 minutes, 53 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 5 minutes, 21 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 4 minutes, 52 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 4 minutes, 19 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 3 minutes, 46 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 15 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 15 seconds.
20250901 120551	500	14	598	45	5	55530000	63

[mbo] 47: num.trees=500; max.depth=14; min.node.size=598; mtry=45 : y = 5.55e+07 : 3494.8 secs : infill_ei

Saved the current state after iteration 48 in the file HT450.RDATA.

20250901 120652	22	7	6	26	5	53304000	64

[mbo] 48: num.trees=22; max.depth=7; min.node.size=6; mtry=26 : y = 5.33e+07 : 55.9 secs : infill_ei

Growing trees.. Progress: 21%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 1 minute, 52 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 18 seconds.
20250901 121941	394	17	1000	11	5	56232000	65

[mbo] 49: num.trees=394; max.depth=17; min.node.size=1000; mtry=11 : y = 5.62e+07 : 768.8 secs : infill_ei

Saved the current state after iteration 50 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 980 points instead of 1000!”

Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 27 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 51 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 14 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 37 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 3 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 16 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 51 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 14 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 40 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 4 minutes, 10 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 6 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 18 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 41 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 10 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 40 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 9 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 5 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 2 minutes, 4 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 16 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 40 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 11 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 37 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 3 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 16 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 46 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 14 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 43 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 4 minutes, 11 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 40 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 8 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 2 minutes, 4 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 33 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
20250901 125443	500	18	386	23	5	55575000	66

[mbo] 50: num.trees=500; max.depth=18; min.node.size=386; mtry=23 : y = 5.56e+07 : 2098.6 secs : infill_ei

Saved the current state after iteration 51 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 971 points instead of 1000!”

Growing trees.. Progress: 82%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 5 seconds.
20250901 125819	123	12	1000	11	5	55617000	67

[mbo] 51: num.trees=123; max.depth=12; min.node.size=1000; mtry=11 : y = 5.56e+07 : 209.7 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 779 points instead of 1000!”

Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 22 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 4 minutes, 47 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 4 minutes, 12 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 3 minutes, 51 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 3 minutes, 17 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 2 minutes, 46 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 22 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 4 minutes, 47 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 3 minutes, 44 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 39 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 5 minutes, 4 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 4 minutes, 31 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 3 minutes, 53 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 3 minutes, 20 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 2 minutes, 46 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 22 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 4 minutes, 55 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 4 minutes, 31 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 2 minutes, 59 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 54 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 14 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 4 minutes, 7 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 3 minutes, 35 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 34 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
20250901 132837	490	10	354	34	5	55605000	68

[mbo] 52: num.trees=490; max.depth=10; min.node.size=354; mtry=34 : y = 5.56e+07 : 1816.8 secs : infill_ei

Saved the current state after iteration 53 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 780 points instead of 1000!”

Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 34 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 57 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 5 minutes, 32 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 5 minutes, 0 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 4 minutes, 26 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 3 minutes, 53 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 3 minutes, 20 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 46 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 36 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 22 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 46 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 20 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 4 minutes, 12 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 3 minutes, 15 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 47 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 17 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 34 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 6 minutes, 9 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 5 minutes, 32 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 5 minutes, 0 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 4 minutes, 28 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 3 minutes, 56 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 3 minutes, 22 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 51 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 34 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 57 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 5 minutes, 28 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 5 minutes, 0 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 4 minutes, 32 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 3 minutes, 58 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 3 minutes, 30 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 2 minutes, 57 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 19 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 6 minutes, 47 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 6 minutes, 3 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 5 minutes, 32 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 5 minutes, 6 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 4 minutes, 38 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 4 minutes, 5 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 3 minutes, 3 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 22 seconds.
20250901 140533	494	30	115	22	5	52353000	69

[mbo] 53: num.trees=494; max.depth=30; min.node.size=115; mtry=22 : y = 5.24e+07 : 2211.7 secs : infill_ei

Saved the current state after iteration 54 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 360 points instead of 1000!”

Growing trees.. Progress: 86%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 6 seconds.
20250901 140938	84	30	1000	11	5	55866000	70

[mbo] 54: num.trees=84; max.depth=30; min.node.size=1000; mtry=11 : y = 5.59e+07 : 240.6 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 360 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 923 points instead of 1000!”

Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 32 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 4 minutes, 0 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 3 minutes, 24 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 2 minutes, 18 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 49 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 4 minutes, 31 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 3 minutes, 50 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 2 minutes, 37 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 49 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 2 minutes, 57 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 40 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 3 minutes, 29 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 2 minutes, 57 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 40 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 3 minutes, 52 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 3 minutes, 21 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 12 seconds.
20250901 143542	171	18	1000	50	5	53682000	71

[mbo] 55: num.trees=171; max.depth=18; min.node.size=1000; mtry=50 : y = 5.37e+07 : 1563.6 secs : infill_ei

Saved the current state after iteration 56 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 330 points instead of 1000!”

Growing trees.. Progress: 25%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 8 seconds.
20250901 144747	500	30	1	6	5	52908000	72

[mbo] 56: num.trees=500; max.depth=30; min.node.size=1; mtry=6 : y = 5.29e+07 : 720.0 secs : infill_ei

Saved the current state after iteration 57 in the file HT450.RDATA.

Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 47 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 13 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 8 minutes, 48 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 8 minutes, 16 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 7 minutes, 52 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 7 minutes, 17 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 6 minutes, 45 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 6 minutes, 13 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 5 minutes, 38 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 5 minutes, 3 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 4 minutes, 30 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 3 minutes, 58 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 25 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 2 minutes, 53 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 22 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 48 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 12 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 19 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 8 minutes, 58 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 8 minutes, 22 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 7 minutes, 54 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 7 minutes, 24 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 6 minutes, 48 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 6 minutes, 18 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 5 minutes, 45 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 5 minutes, 16 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 4 minutes, 15 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 3 minutes, 11 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 13 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 29 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 11 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 8 minutes, 38 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 7 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 7 minutes, 32 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 7 minutes, 0 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 6 minutes, 21 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 5 minutes, 47 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 5 minutes, 13 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 4 minutes, 8 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 3 minutes, 35 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 3 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 23 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 13 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 8 minutes, 35 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 8 minutes, 10 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 7 minutes, 37 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 7 minutes, 7 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 6 minutes, 36 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 6 minutes, 5 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 5 minutes, 32 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 4 minutes, 57 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 4 minutes, 25 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 3 minutes, 54 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 21 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 49 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 2 minutes, 17 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 33 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 38 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 9 minutes, 11 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 8 minutes, 34 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 7 minutes, 56 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 7 minutes, 20 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 6 minutes, 45 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 6 minutes, 13 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 5 minutes, 40 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 5 minutes, 9 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 4 minutes, 40 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 4 minutes, 11 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 3 minutes, 8 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 22 seconds.
20250901 154048	499	23	999	33	5	55104000	73

[mbo] 57: num.trees=499; max.depth=23; min.node.size=999; mtry=33 : y = 5.51e+07 : 3176.1 secs : infill_ei

Saved the current state after iteration 58 in the file HT450.RDATA.

Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 42 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 38 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 38 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 1 minute, 33 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 48 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 38 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 0 seconds.
20250901 155730	386	10	1	22	5	55464000	74

[mbo] 58: num.trees=386; max.depth=10; min.node.size=1; mtry=22 : y = 5.55e+07 : 994.8 secs : infill_ei

Saved the current state after iteration 59 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 887 points instead of 1000!”

Growing trees.. Progress: 31%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 10 seconds.
20250901 160719	500	20	242	5	5	55347000	75

[mbo] 59: num.trees=500; max.depth=20; min.node.size=242; mtry=5 : y = 5.53e+07 : 582.9 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 874 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 993 points instead of 1000!”

Growing trees.. Progress: 90%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 4 seconds.
20250901 161031	29	30	1000	31	5	51735000	76

[mbo] 60: num.trees=29; max.depth=30; min.node.size=1000; mtry=31 : y = 5.17e+07 : 191.3 secs : infill_ei

Saved the current state after iteration 61 in the file HT450.RDATA.

20250901 161311	20	13	475	50	5	53586000	77

[mbo] 61: num.trees=20; max.depth=13; min.node.size=475; mtry=50 : y = 5.36e+07 : 155.5 secs : infill_ei

Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 52 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 2 minutes, 18 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 48 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 47 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 47 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 11 seconds.
20250901 163047	500	13	331	13	5	55026000	78

[mbo] 62: num.trees=500; max.depth=13; min.node.size=331; mtry=13 : y = 5.5e+07 : 1056.2 secs : infill_ei

Saved the current state after iteration 63 in the file HT450.RDATA.

Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 21 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 3 minutes, 54 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 3 minutes, 21 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 2 minutes, 47 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 2 minutes, 16 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 21 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 3 minutes, 50 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 3 minutes, 18 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 2 minutes, 47 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 2 minutes, 16 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 13 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 41 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 3 minutes, 10 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 30 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 3 minutes, 50 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 3 minutes, 19 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 2 minutes, 47 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 2 minutes, 16 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 30 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 3 minutes, 55 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 3 minutes, 18 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 5 seconds.
20250901 165616	321	13	496	32	5	55908000	79

[mbo] 63: num.trees=321; max.depth=13; min.node.size=496; mtry=32 : y = 5.59e+07 : 1524.5 secs : infill_ei

Saved the current state after iteration 64 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 964 points instead of 1000!”

Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 41 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 3 minutes, 6 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 29 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 2 minutes, 57 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 1 minute, 48 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 2 minutes, 59 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 3 minutes, 25 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 2 minutes, 53 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 56 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 18 seconds.
20250901 171902	285	23	1000	25	5	54651000	80

[mbo] 64: num.trees=285; max.depth=23; min.node.size=1000; mtry=25 : y = 5.47e+07 : 1361.1 secs : infill_ei

Saved the current state after iteration 65 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 944 points instead of 1000!”

Growing trees.. Progress: 98%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 0 seconds.
20250901 172205	500	1	582	48	5	43353000	81

[mbo] 65: num.trees=500; max.depth=1; min.node.size=582; mtry=48 : y = 4.34e+07 : 178.4 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 450 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 360 points instead of 1000!”

Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 34 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 45 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 9 minutes, 16 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 8 minutes, 42 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 7 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 7 minutes, 39 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 7 minutes, 8 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 6 minutes, 37 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 6 minutes, 6 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 5 minutes, 33 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 5 minutes, 2 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 4 minutes, 30 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 59 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 3 minutes, 28 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 1 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 24 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 34 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 59 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 9 minutes, 10 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 8 minutes, 49 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 17 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 7 minutes, 48 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 7 minutes, 14 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 6 minutes, 42 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 6 minutes, 14 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 5 minutes, 45 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 5 minutes, 15 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 4 minutes, 42 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 41 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 9 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 38 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 34 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 59 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 20 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 8 minutes, 56 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 25 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 7 minutes, 53 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 7 minutes, 26 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 6 minutes, 53 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 6 minutes, 20 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 5 minutes, 46 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 5 minutes, 16 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 4 minutes, 43 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 4 minutes, 13 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 40 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 10 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 11 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 6 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 5 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 11 minutes, 15 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 10 minutes, 18 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 31 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 8 minutes, 57 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 24 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 7 minutes, 51 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 7 minutes, 18 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 6 minutes, 53 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 6 minutes, 23 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 5 minutes, 47 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 5 minutes, 12 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 4 minutes, 40 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 6 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 3 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 55 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 13 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 45 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 8 minutes, 56 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 21 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 7 minutes, 51 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 7 minutes, 16 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 6 minutes, 42 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 6 minutes, 10 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 5 minutes, 37 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 5 minutes, 5 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 4 minutes, 31 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 3 minutes, 57 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 3 minutes, 24 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 51 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 7 seconds.
20250901 181812	494	13	1000	49	5	55710000	82

[mbo] 66: num.trees=494; max.depth=13; min.node.size=1000; mtry=49 : y = 5.57e+07 : 3366.2 secs : infill_ei

Saved the current state after iteration 67 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 450 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 648 points instead of 1000!”

Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 49 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 36 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 9 minutes, 1 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 8 minutes, 32 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 7 minutes, 57 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 7 minutes, 24 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 6 minutes, 50 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 6 minutes, 18 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 5 minutes, 48 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 5 minutes, 15 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 4 minutes, 42 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 4 minutes, 10 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 2 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 24 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 8 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 49 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 24 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 8 minutes, 50 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 20 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 7 minutes, 49 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 7 minutes, 16 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 6 minutes, 45 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 6 minutes, 11 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 5 minutes, 39 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 5 minutes, 7 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 4 minutes, 33 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 3 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 42 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 53 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 18 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 8 minutes, 46 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 11 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 7 minutes, 44 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 7 minutes, 14 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 6 minutes, 42 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 6 minutes, 10 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 5 minutes, 39 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 5 minutes, 8 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 4 minutes, 37 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 6 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 5 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 26 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 27 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 36 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 9 minutes, 15 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 8 minutes, 47 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 18 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 7 minutes, 47 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 7 minutes, 14 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 6 minutes, 45 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 6 minutes, 12 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 5 minutes, 41 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 5 minutes, 9 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 4 minutes, 35 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 3 minutes, 32 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 1 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 59 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 42 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 9 minutes, 57 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 27 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 8 minutes, 57 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 31 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 8 minutes, 1 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 7 minutes, 28 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 6 minutes, 54 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 6 minutes, 23 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 5 minutes, 50 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 5 minutes, 17 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 4 minutes, 14 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 14 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 2 seconds.
20250901 191409	500	17	1000	39	5	54990000	83

[mbo] 67: num.trees=500; max.depth=17; min.node.size=1000; mtry=39 : y = 5.5e+07 : 3354.1 secs : infill_ei

Saved the current state after iteration 68 in the file HT450.RDATA.

Growing trees.. Progress: 30%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 8 seconds.
20250901 192326	166	19	1000	18	5	53916000	84

[mbo] 68: num.trees=166; max.depth=19; min.node.size=1000; mtry=18 : y = 5.39e+07 : 549.4 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 252 points instead of 1000!”

Growing trees.. Progress: 3%. Estimated remaining time: 15 minutes, 9 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 14 minutes, 23 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 14 minutes, 5 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 13 minutes, 32 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 12 minutes, 58 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 12 minutes, 21 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 11 minutes, 49 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 11 minutes, 20 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 10 minutes, 52 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 10 minutes, 18 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 9 minutes, 44 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 9 minutes, 11 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 8 minutes, 37 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 8 minutes, 0 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 7 minutes, 27 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 6 minutes, 52 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 6 minutes, 18 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 5 minutes, 44 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 5 minutes, 10 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 4 minutes, 36 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 3 minutes, 35 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 3 minutes, 1 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 54 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 15 minutes, 9 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 14 minutes, 23 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 14 minutes, 4 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 13 minutes, 25 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 13 minutes, 1 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 12 minutes, 29 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 11 minutes, 57 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 11 minutes, 23 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 10 minutes, 49 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 10 minutes, 14 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 9 minutes, 40 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 9 minutes, 4 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 8 minutes, 32 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 8 minutes, 1 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 7 minutes, 29 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 6 minutes, 55 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 6 minutes, 21 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 5 minutes, 47 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 5 minutes, 13 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 4 minutes, 5 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 3 minutes, 32 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 15 minutes, 37 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 15 minutes, 36 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 15 minutes, 4 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 14 minutes, 32 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 13 minutes, 54 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 13 minutes, 19 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 12 minutes, 35 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 12 minutes, 5 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 11 minutes, 33 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 11 minutes, 5 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 10 minutes, 27 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 10 minutes, 2 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 9 minutes, 27 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 8 minutes, 55 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 8 minutes, 20 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 7 minutes, 50 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 7 minutes, 19 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 6 minutes, 51 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 6 minutes, 20 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 5 minutes, 48 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 5 minutes, 14 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 4 minutes, 43 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 4 minutes, 11 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 3 minutes, 38 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 3 minutes, 6 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 35 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 16 minutes, 42 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 15 minutes, 38 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 14 minutes, 56 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 14 minutes, 25 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 13 minutes, 49 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 13 minutes, 7 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 12 minutes, 41 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 12 minutes, 8 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 11 minutes, 38 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 11 minutes, 7 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 10 minutes, 29 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 10 minutes, 4 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 9 minutes, 33 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 9 minutes, 3 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 8 minutes, 26 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 7 minutes, 52 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 7 minutes, 21 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 6 minutes, 44 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 6 minutes, 12 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 5 minutes, 38 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 5 minutes, 6 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 4 minutes, 35 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 4 minutes, 1 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 3 minutes, 28 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 2 minutes, 57 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 15 minutes, 37 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 15 minutes, 5 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 14 minutes, 22 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 14 minutes, 0 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 13 minutes, 28 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 12 minutes, 52 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 12 minutes, 19 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 11 minutes, 44 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 11 minutes, 14 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 10 minutes, 40 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 10 minutes, 2 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 9 minutes, 32 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 8 minutes, 55 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 8 minutes, 21 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 7 minutes, 50 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 7 minutes, 16 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 6 minutes, 46 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 6 minutes, 15 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 5 minutes, 45 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 5 minutes, 15 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 4 minutes, 10 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 3 minutes, 40 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 3 minutes, 6 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 33 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 59 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 24 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 17 seconds.
20250901 204425	500	21	1000	50	5	55017000	85

[mbo] 69: num.trees=500; max.depth=21; min.node.size=1000; mtry=50 : y = 5.5e+07 : 4858.7 secs : infill_ei

Saved the current state after iteration 70 in the file HT450.RDATA.

Growing trees.. Progress: 21%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 24 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 57 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 25 seconds.
20250901 205747	274	10	381	25	5	55512000	86

[mbo] 70: num.trees=274; max.depth=10; min.node.size=381; mtry=25 : y = 5.55e+07 : 798.0 secs : infill_ei

Saved the current state after iteration 71 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 930 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 640 points instead of 1000!”

Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 6 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 25 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 5 minutes, 0 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 4 minutes, 30 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 9 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 3 minutes, 5 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 50 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 47 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 21 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 4 minutes, 48 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 4 minutes, 17 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 3 minutes, 47 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 3 minutes, 16 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 16 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 1 minute, 48 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 12 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 47 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 5 minutes, 7 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 4 minutes, 33 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 4 minutes, 0 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 2 minutes, 59 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 56 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 16 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 4 minutes, 11 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 3 minutes, 40 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 3 minutes, 8 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 2 minutes, 36 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 4 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 47 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 21 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 4 minutes, 48 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 4 minutes, 13 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 3 minutes, 42 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 3 minutes, 9 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 2 minutes, 38 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 1 seconds.
20250901 213034	500	9	1	41	5	54516000	87

[mbo] 71: num.trees=500; max.depth=9; min.node.size=1; mtry=41 : y = 5.45e+07 : 1959.9 secs : infill_ei

Saved the current state after iteration 72 in the file HT450.RDATA.

Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 5 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 2 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 36 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 1 minute, 33 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 1 minute, 33 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
20250901 214146	157	13	1000	29	5	54735000	88

[mbo] 72: num.trees=157; max.depth=13; min.node.size=1000; mtry=29 : y = 5.47e+07 : 669.1 secs : infill_ei

Saved the current state after iteration 73 in the file HT450.RDATA.

Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 47 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 5 minutes, 16 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 4 minutes, 13 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 3 minutes, 44 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 3 minutes, 12 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 43 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 13 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 12 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 56 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 21 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 4 minutes, 54 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 4 minutes, 20 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 3 minutes, 47 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 3 minutes, 15 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 43 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 8 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 16 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 5 minutes, 40 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 7 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 4 minutes, 35 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 4 minutes, 3 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 3 minutes, 29 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 24 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 47 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 20 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 4 minutes, 51 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 4 minutes, 18 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 3 minutes, 15 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 46 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 16 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 56 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 25 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 5 minutes, 0 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 4 minutes, 28 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 3 minutes, 57 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 3 minutes, 24 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 2 minutes, 22 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 14 seconds.
20250901 221549	500	22	557	21	5	53895000	89

[mbo] 73: num.trees=500; max.depth=22; min.node.size=557; mtry=21 : y = 5.39e+07 : 2035.7 secs : infill_ei

Saved the current state after iteration 74 in the file HT450.RDATA.

20250901 221718	20	10	423	33	5	52314000	90

[mbo] 74: num.trees=20; max.depth=10; min.node.size=423; mtry=33 : y = 5.23e+07 : 84.3 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 932 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 977 points instead of 1000!”

Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 13 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 52 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 13 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 9 minutes, 38 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 9 minutes, 4 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 8 minutes, 39 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 8 minutes, 7 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 7 minutes, 37 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 7 minutes, 5 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 6 minutes, 29 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 5 minutes, 59 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 5 minutes, 28 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 4 minutes, 56 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 23 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 54 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 20 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 48 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 11 minutes, 3 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 26 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 52 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 9 minutes, 14 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 38 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 8 minutes, 4 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 7 minutes, 40 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 7 minutes, 10 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 6 minutes, 43 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 6 minutes, 13 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 5 minutes, 40 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 5 minutes, 10 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 4 minutes, 38 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 4 minutes, 7 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 3 minutes, 32 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 59 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 11 minutes, 24 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 47 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 20 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 9 minutes, 46 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 17 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 8 minutes, 44 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 8 minutes, 14 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 7 minutes, 43 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 7 minutes, 14 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 6 minutes, 44 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 6 minutes, 12 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 5 minutes, 38 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 5 minutes, 7 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 4 minutes, 35 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 4 minutes, 3 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 31 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 30 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 26 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 13 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 37 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 10 minutes, 3 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 9 minutes, 35 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 9 minutes, 7 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 8 minutes, 41 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 8 minutes, 11 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 7 minutes, 42 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 7 minutes, 9 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 6 minutes, 35 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 6 minutes, 4 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 5 minutes, 33 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 5 minutes, 2 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 4 minutes, 31 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 4 minutes, 0 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 28 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 56 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 47 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 11 minutes, 9 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 10 minutes, 24 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 9 minutes, 49 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 9 minutes, 20 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 8 minutes, 46 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 8 minutes, 18 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 7 minutes, 49 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 7 minutes, 16 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 6 minutes, 42 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 6 minutes, 7 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 5 minutes, 30 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 4 minutes, 55 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 22 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 53 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 20 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 48 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 17 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 11 seconds.
20250901 231750	500	30	951	37	5	55020000	91

[mbo] 75: num.trees=500; max.depth=30; min.node.size=951; mtry=37 : y = 5.5e+07 : 3631.4 secs : infill_ei

Saved the current state after iteration 76 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 756 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 975 points instead of 1000!”

20250901 231831	20	30	79	5	5	47085000	92

[mbo] 76: num.trees=20; max.depth=30; min.node.size=79; mtry=5 : y = 4.71e+07 : 35.4 secs : infill_ei

Growing trees.. Progress: 51%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 28 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 0 seconds.
20250901 232406	152	23	1000	12	5	55104000	93

[mbo] 77: num.trees=152; max.depth=23; min.node.size=1000; mtry=12 : y = 5.51e+07 : 334.1 secs : infill_ei

Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 42 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 2 minutes, 18 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 16 seconds.
20250901 234143	500	30	570	11	5	54759000	94

[mbo] 78: num.trees=500; max.depth=30; min.node.size=570; mtry=11 : y = 5.48e+07 : 1056.2 secs : infill_ei

Saved the current state after iteration 79 in the file HT450.RDATA.

Growing trees.. Progress: 23%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 1 minute, 47 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 36 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 6 seconds.
20250901 235333	295	7	1	34	5	54255000	95

[mbo] 79: num.trees=295; max.depth=7; min.node.size=1; mtry=34 : y = 5.43e+07 : 706.1 secs : infill_ei

Saved the current state after iteration 80 in the file HT450.RDATA.

Growing trees.. Progress: 27%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 25 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 28 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 22 seconds.
20250902 000414	281	18	1	11	5	52707000	96

[mbo] 80: num.trees=281; max.depth=18; min.node.size=1; mtry=11 : y = 5.27e+07 : 634.6 secs : infill_ei

Saved the current state after iteration 81 in the file HT450.RDATA.

Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 36 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 5 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 2 minutes, 11 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 1 minute, 39 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 36 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 4 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 1 minute, 36 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 34 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 2 seconds.
20250902 002118	500	17	403	11	5	54945000	97

[mbo] 81: num.trees=500; max.depth=17; min.node.size=403; mtry=11 : y = 5.49e+07 : 1018.5 secs : infill_ei

Saved the current state after iteration 82 in the file HT450.RDATA.

Growing trees.. Progress: 13%. Estimated remaining time: 3 minutes, 23 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 2 minutes, 47 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 2 minutes, 17 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 40 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 3 minutes, 23 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 3 minutes, 39 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 3 minutes, 6 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 2 minutes, 34 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 27 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 2 minutes, 51 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 1 minute, 50 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 15 seconds.
20250902 004214	500	15	78	14	5	54825000	98

[mbo] 82: num.trees=500; max.depth=15; min.node.size=78; mtry=14 : y = 5.48e+07 : 1251.6 secs : infill_ei

Saved the current state after iteration 83 in the file HT450.RDATA.

Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 20 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 47 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 5 minutes, 10 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 4 minutes, 34 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 4 minutes, 0 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 3 minutes, 25 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 54 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 18 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 8 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 37 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 5 minutes, 16 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 4 minutes, 50 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 4 minutes, 20 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 3 minutes, 51 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 24 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 7 minutes, 4 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 6 minutes, 19 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 5 minutes, 38 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 5 minutes, 8 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 4 minutes, 28 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 3 minutes, 55 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 3 minutes, 30 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 3 minutes, 1 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 22 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 33 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 54 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 5 minutes, 22 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 4 minutes, 45 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 4 minutes, 12 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 3 minutes, 41 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 3 minutes, 7 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 2 minutes, 34 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 30 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 26 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 54 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 5 minutes, 15 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 4 minutes, 40 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 4 minutes, 7 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 3 minutes, 1 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 57 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 53 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 23 seconds.
20250902 011612	374	11	339	44	5	55017000	99

[mbo] 83: num.trees=374; max.depth=11; min.node.size=339; mtry=44 : y = 5.5e+07 : 2033.9 secs : infill_ei

Saved the current state after iteration 84 in the file HT450.RDATA.

Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 41 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 16 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 4 minutes, 43 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 4 minutes, 16 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 3 minutes, 43 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 3 minutes, 10 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 2 minutes, 38 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 9 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 37 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 32 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 52 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 21 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 4 minutes, 46 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 4 minutes, 13 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 3 minutes, 42 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 3 minutes, 11 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 2 minutes, 38 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 2 minutes, 6 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 3 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 31 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 4 minutes, 56 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 4 minutes, 22 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 3 minutes, 49 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 3 minutes, 16 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 5 minutes, 52 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 26 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 4 minutes, 53 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 4 minutes, 23 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 3 minutes, 50 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 3 minutes, 18 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 47 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 2 minutes, 17 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 6 minutes, 3 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 5 minutes, 26 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 4 minutes, 53 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 4 minutes, 18 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 3 minutes, 47 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 3 minutes, 17 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 37 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 5 seconds.
20250902 014917	433	15	516	28	5	55008000	100

[mbo] 84: num.trees=433; max.depth=15; min.node.size=516; mtry=28 : y = 5.5e+07 : 1979.9 secs : infill_ei

Saved the current state after iteration 85 in the file HT450.RDATA.

Growing trees.. Progress: 5%. Estimated remaining time: 9 minutes, 57 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 47 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 9 minutes, 16 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 8 minutes, 38 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 8 minutes, 11 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 7 minutes, 32 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 7 minutes, 0 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 6 minutes, 29 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 5 minutes, 57 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 5 minutes, 26 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 4 minutes, 54 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 4 minutes, 22 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 3 minutes, 51 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 3 minutes, 17 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 2 minutes, 46 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 12 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 11 minutes, 2 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 10 minutes, 30 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 48 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 9 minutes, 19 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 8 minutes, 49 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 8 minutes, 22 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 7 minutes, 55 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 7 minutes, 24 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 6 minutes, 55 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 6 minutes, 24 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 5 minutes, 56 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 5 minutes, 25 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 4 minutes, 53 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 18 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 49 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 18 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 2 minutes, 47 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 15 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 41 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 32 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 47 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 17 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 8 minutes, 53 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 20 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 7 minutes, 50 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 7 minutes, 20 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 6 minutes, 49 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 6 minutes, 18 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 5 minutes, 46 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 5 minutes, 13 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 4 minutes, 41 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 4 minutes, 8 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 1 minute, 59 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 32 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 9 minutes, 56 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 26 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 8 minutes, 53 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 20 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 7 minutes, 45 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 7 minutes, 15 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 6 minutes, 43 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 6 minutes, 11 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 5 minutes, 39 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 5 minutes, 6 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 4 minutes, 32 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 2 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 3 minutes, 30 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 52 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 5%. Estimated remaining time: 10 minutes, 52 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 10 minutes, 5 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 9 minutes, 23 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 8 minutes, 50 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 8 minutes, 15 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 7 minutes, 46 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 7 minutes, 12 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 6 minutes, 40 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 6 minutes, 7 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 5 minutes, 33 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 5 minutes, 2 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 4 minutes, 30 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 3 minutes, 58 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 2 minutes, 55 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 15 seconds.
20250902 024555	492	19	481	37	5	54435000	101

[mbo] 85: num.trees=492; max.depth=19; min.node.size=481; mtry=37 : y = 5.44e+07 : 3392.7 secs : infill_ei

Saved the current state after iteration 86 in the file HT450.RDATA.

Growing trees.. Progress: 4%. Estimated remaining time: 13 minutes, 4 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 12 minutes, 24 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 11 minutes, 57 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 11 minutes, 22 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 10 minutes, 52 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 10 minutes, 17 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 9 minutes, 46 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 9 minutes, 17 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 8 minutes, 43 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 8 minutes, 15 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 7 minutes, 43 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 7 minutes, 9 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 6 minutes, 35 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 6 minutes, 5 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 5 minutes, 32 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 59 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 4 minutes, 28 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 55 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 3 minutes, 23 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 50 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 2 minutes, 17 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 11 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 39 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 14 minutes, 20 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 13 minutes, 11 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 12 minutes, 26 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 12 minutes, 5 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 11 minutes, 21 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 10 minutes, 48 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 10 minutes, 13 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 9 minutes, 46 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 9 minutes, 11 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 8 minutes, 42 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 8 minutes, 9 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 7 minutes, 35 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 7 minutes, 4 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 6 minutes, 33 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 6 minutes, 2 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 5 minutes, 29 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 4 minutes, 57 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 4 minutes, 22 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 3 minutes, 48 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 3 minutes, 16 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 12 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 38 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 1 minute, 4 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 13 minutes, 55 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 13 minutes, 10 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 12 minutes, 41 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 12 minutes, 5 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 11 minutes, 35 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 11 minutes, 4 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 10 minutes, 30 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 9 minutes, 59 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 9 minutes, 29 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 8 minutes, 54 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 8 minutes, 18 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 7 minutes, 44 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 7 minutes, 7 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 6 minutes, 35 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 6 minutes, 2 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 5 minutes, 32 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 4 minutes, 59 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 4 minutes, 27 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 57 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 3 minutes, 24 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 52 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 18 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 13 minutes, 30 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 12 minutes, 48 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 12 minutes, 19 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 11 minutes, 48 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 11 minutes, 25 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 10 minutes, 52 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 10 minutes, 22 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 9 minutes, 48 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 9 minutes, 12 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 8 minutes, 37 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 8 minutes, 5 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 7 minutes, 32 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 6 minutes, 58 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 6 minutes, 23 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 5 minutes, 49 seconds.
Growing trees.. Progress: 62%. Estimated remaining time: 5 minutes, 17 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 4 minutes, 43 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 4 minutes, 11 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 3 minutes, 37 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 2 minutes, 32 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 56 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 13 minutes, 4 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 12 minutes, 33 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 12 minutes, 2 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 11 minutes, 37 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 11 minutes, 9 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 10 minutes, 39 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 10 minutes, 9 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 9 minutes, 35 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 9 minutes, 2 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 8 minutes, 31 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 8 minutes, 0 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 7 minutes, 30 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 6 minutes, 58 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 6 minutes, 29 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 5 minutes, 57 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 5 minutes, 26 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 4 minutes, 53 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 4 minutes, 22 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 3 minutes, 49 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 3 minutes, 15 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 2 minutes, 41 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 2 minutes, 8 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 34 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
20250902 035645	500	17	777	50	5	54927000	102

[mbo] 86: num.trees=500; max.depth=17; min.node.size=777; mtry=50 : y = 5.49e+07 : 4244.4 secs : infill_ei

Saved the current state after iteration 87 in the file HT450.RDATA.

Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 10 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 4 minutes, 36 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 4 minutes, 0 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 3 minutes, 27 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 2 minutes, 55 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 2 minutes, 21 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 0 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 4 minutes, 28 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 3 minutes, 53 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 3 minutes, 19 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 2 minutes, 48 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 2 minutes, 17 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 45 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 13 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 10 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 3 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 59 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 27 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 55 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 24 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 0 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 4 minutes, 33 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 3 minutes, 30 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 25 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 12 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 4 minutes, 4 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 3 minutes, 30 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 58 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 26 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 52 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 18 seconds.
20250902 042529	310	19	1000	32	5	55311000	103

[mbo] 87: num.trees=310; max.depth=19; min.node.size=1000; mtry=32 : y = 5.53e+07 : 1718.7 secs : infill_ei

Saved the current state after iteration 88 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 999 points instead of 1000!”

Growing trees.. Progress: 27%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 23 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 22 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 1 minute, 25 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 22 seconds.
20250902 043542	296	8	1000	26	5	54153000	104

[mbo] 88: num.trees=296; max.depth=8; min.node.size=1000; mtry=26 : y = 5.42e+07 : 607.0 secs : infill_ei

Saved the current state after iteration 89 in the file HT450.RDATA.

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 594 points instead of 1000!”

Growing trees.. Progress: 33%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 59 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 28 seconds.
Growing trees.. Progress: 33%. Estimated remaining time: 1 minute, 2 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 31 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 1 minute, 1 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
20250902 044439	499	17	98	5	5	54942000	105

[mbo] 89: num.trees=499; max.depth=17; min.node.size=98; mtry=5 : y = 5.49e+07 : 531.0 secs : infill_ei

Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 270 points instead of 1000!”
Warning message in generateDesign(control$infill.opt.focussearch.points, ps.local, :
“generateDesign could only produce 939 points instead of 1000!”

Growing trees.. Progress: 4%. Estimated remaining time: 13 minutes, 30 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 12 minutes, 36 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 11 minutes, 57 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 11 minutes, 22 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 10 minutes, 48 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 10 minutes, 18 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 9 minutes, 47 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 9 minutes, 14 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 8 minutes, 43 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 8 minutes, 14 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 7 minutes, 42 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 7 minutes, 8 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 6 minutes, 31 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 6 minutes, 1 seconds.
Growing trees.. Progress: 59%. Estimated remaining time: 5 minutes, 26 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 4 minutes, 54 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 4 minutes, 22 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 3 minutes, 49 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 3 minutes, 18 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 2 minutes, 13 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 43 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 13 minutes, 12 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 12 minutes, 7 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 11 minutes, 38 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 11 minutes, 27 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 10 minutes, 52 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 10 minutes, 17 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 9 minutes, 44 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 9 minutes, 11 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 8 minutes, 38 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 8 minutes, 5 seconds.
Growing trees.. Progress: 44%. Estimated remaining time: 7 minutes, 34 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 7 minutes, 1 seconds.
Growing trees.. Progress: 52%. Estimated remaining time: 6 minutes, 29 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 5 minutes, 57 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 5 minutes, 24 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 4 minutes, 52 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 4 minutes, 19 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 49 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 3 minutes, 16 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 44 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 11 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 41 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 1 minute, 7 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 35 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 3 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 13 minutes, 30 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 12 minutes, 48 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 12 minutes, 26 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 11 minutes, 48 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 11 minutes, 17 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 10 minutes, 49 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 10 minutes, 14 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 9 minutes, 45 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 9 minutes, 13 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 8 minutes, 43 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 8 minutes, 15 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 7 minutes, 43 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 7 minutes, 10 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 6 minutes, 39 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 6 minutes, 5 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 5 minutes, 34 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 5 minutes, 1 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 4 minutes, 29 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 3 minutes, 57 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 3 minutes, 23 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 51 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 18 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 13 minutes, 30 seconds.
Growing trees.. Progress: 8%. Estimated remaining time: 12 minutes, 45 seconds.
Growing trees.. Progress: 12%. Estimated remaining time: 12 minutes, 11 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 11 minutes, 37 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 11 minutes, 0 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 10 minutes, 25 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 10 minutes, 0 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 9 minutes, 29 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 8 minutes, 56 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 8 minutes, 26 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 7 minutes, 54 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 7 minutes, 22 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 6 minutes, 57 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 6 minutes, 27 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 5 minutes, 54 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 5 minutes, 21 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 4 minutes, 52 seconds.
Growing trees.. Progress: 69%. Estimated remaining time: 4 minutes, 21 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 3 minutes, 49 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 3 minutes, 18 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 1 minute, 42 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 1 minute, 10 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 6 seconds.
Growing trees.. Progress: 4%. Estimated remaining time: 14 minutes, 16 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 13 minutes, 8 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 12 minutes, 41 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 11 minutes, 59 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 11 minutes, 26 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 10 minutes, 57 seconds.
Growing trees.. Progress: 27%. Estimated remaining time: 10 minutes, 23 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 9 minutes, 50 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 9 minutes, 19 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 8 minutes, 51 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 8 minutes, 22 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 7 minutes, 49 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 7 minutes, 17 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 6 minutes, 47 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 6 minutes, 13 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 5 minutes, 43 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 5 minutes, 10 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 4 minutes, 40 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 4 minutes, 7 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 3 minutes, 34 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 1 minute, 56 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 98%. Estimated remaining time: 17 seconds.
20250902 055533	500	26	977	44	5	55326000	106

[mbo] 90: num.trees=500; max.depth=26; min.node.size=977; mtry=44 : y = 5.53e+07 : 4253.1 secs : infill_ei

Saved the current state after iteration 91 in the file HT450.RDATA.

Growing trees.. Progress: 4%. Estimated remaining time: 13 minutes, 50 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 13 minutes, 8 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 12 minutes, 48 seconds.
Growing trees.. Progress: 15%. Estimated remaining time: 12 minutes, 11 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 11 minutes, 35 seconds.
Growing trees.. Progress: 23%. Estimated remaining time: 10 minutes, 57 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 10 minutes, 27 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 9 minutes, 50 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 9 minutes, 22 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 8 minutes, 48 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 8 minutes, 18 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 7 minutes, 44 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 7 minutes, 10 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 6 minutes, 39 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 6 minutes, 6 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 5 minutes, 35 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 5 minutes, 4 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 4 minutes, 33 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 4 minutes, 3 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 3 minutes, 33 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 3 minutes, 0 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 2 minutes, 0 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 29 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 58 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 14 minutes, 40 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 14 minutes, 10 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 13 minutes, 47 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 13 minutes, 19 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 12 minutes, 59 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 12 minutes, 18 seconds.
Growing trees.. Progress: 24%. Estimated remaining time: 11 minutes, 54 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 11 minutes, 22 seconds.
Growing trees.. Progress: 31%. Estimated remaining time: 11 minutes, 4 seconds.
Growing trees.. Progress: 34%. Estimated remaining time: 10 minutes, 38 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 10 minutes, 9 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 9 minutes, 38 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 9 minutes, 10 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 8 minutes, 41 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 8 minutes, 9 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 7 minutes, 39 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 7 minutes, 9 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 6 minutes, 33 seconds.
Growing trees.. Progress: 63%. Estimated remaining time: 5 minutes, 59 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 5 minutes, 27 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 4 minutes, 54 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 4 minutes, 20 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 3 minutes, 46 seconds.
Growing trees.. Progress: 80%. Estimated remaining time: 3 minutes, 15 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 40 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 1 minute, 9 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 38 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 7 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 17 minutes, 47 seconds.
Growing trees.. Progress: 6%. Estimated remaining time: 16 minutes, 23 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 15 minutes, 34 seconds.
Growing trees.. Progress: 13%. Estimated remaining time: 14 minutes, 54 seconds.
Growing trees.. Progress: 16%. Estimated remaining time: 14 minutes, 17 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 13 minutes, 44 seconds.
Growing trees.. Progress: 22%. Estimated remaining time: 13 minutes, 13 seconds.
Growing trees.. Progress: 26%. Estimated remaining time: 12 minutes, 41 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 12 minutes, 4 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 11 minutes, 28 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 10 minutes, 55 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 10 minutes, 22 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 9 minutes, 47 seconds.
Growing trees.. Progress: 45%. Estimated remaining time: 9 minutes, 17 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 8 minutes, 44 seconds.
Growing trees.. Progress: 51%. Estimated remaining time: 8 minutes, 10 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 7 minutes, 38 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 7 minutes, 8 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 6 minutes, 35 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 6 minutes, 0 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 5 minutes, 28 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 4 minutes, 55 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 4 minutes, 18 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 3 minutes, 41 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 3 minutes, 4 seconds.
Growing trees.. Progress: 85%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 52 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 99%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 14 minutes, 40 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 13 minutes, 56 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 13 minutes, 12 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 12 minutes, 53 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 12 minutes, 25 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 11 minutes, 58 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 11 minutes, 26 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 10 minutes, 54 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 10 minutes, 21 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 9 minutes, 47 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 9 minutes, 15 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 8 minutes, 37 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 8 minutes, 9 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 7 minutes, 35 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 7 minutes, 3 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 6 minutes, 30 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 5 minutes, 56 seconds.
Growing trees.. Progress: 64%. Estimated remaining time: 5 minutes, 26 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 4 minutes, 53 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 4 minutes, 20 seconds.
Growing trees.. Progress: 75%. Estimated remaining time: 3 minutes, 45 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 3 minutes, 13 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 2 minutes, 40 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 2 minutes, 7 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 1 minute, 35 seconds.
Growing trees.. Progress: 93%. Estimated remaining time: 1 minute, 3 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 30 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 1 seconds.
Growing trees.. Progress: 3%. Estimated remaining time: 14 minutes, 40 seconds.
Growing trees.. Progress: 7%. Estimated remaining time: 13 minutes, 19 seconds.
Growing trees.. Progress: 11%. Estimated remaining time: 13 minutes, 12 seconds.
Growing trees.. Progress: 14%. Estimated remaining time: 12 minutes, 41 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 12 minutes, 9 seconds.
Growing trees.. Progress: 21%. Estimated remaining time: 11 minutes, 37 seconds.
Growing trees.. Progress: 25%. Estimated remaining time: 11 minutes, 6 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 10 minutes, 31 seconds.
Growing trees.. Progress: 32%. Estimated remaining time: 9 minutes, 57 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 9 minutes, 26 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 8 minutes, 56 seconds.
Growing trees.. Progress: 43%. Estimated remaining time: 8 minutes, 25 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 7 minutes, 53 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 7 minutes, 20 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 6 minutes, 46 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 6 minutes, 14 seconds.
Growing trees.. Progress: 61%. Estimated remaining time: 5 minutes, 42 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 5 minutes, 11 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 4 minutes, 39 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 4 minutes, 7 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 3 minutes, 35 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 3 minutes, 3 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 2 minutes, 31 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 2 minutes, 1 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 1 minute, 28 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 54 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 22 seconds.
20250902 071346	500	30	566	45	5	54117000	107

[mbo] 91: num.trees=500; max.depth=30; min.node.size=566; mtry=45 : y = 5.41e+07 : 4686.3 secs : infill_ei

Saved the current state after iteration 92 in the file HT450.RDATA.

Growing trees.. Progress: 41%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 42%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 12 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 83%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 41%. Estimated remaining time: 44 seconds.
Growing trees.. Progress: 82%. Estimated remaining time: 13 seconds.
20250902 072039	200	18	1000	12	5	55242000	108

[mbo] 92: num.trees=200; max.depth=18; min.node.size=1000; mtry=12 : y = 5.52e+07 : 409.1 secs : infill_ei

Growing trees.. Progress: 75%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 12 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 11 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 11 seconds.
20250902 072515	465	19	999	2	5	53028000	109

[mbo] 93: num.trees=465; max.depth=19; min.node.size=999; mtry=2 : y = 5.3e+07 : 275.2 secs : infill_ei

Saved the current state after iteration 94 in the file HT450.RDATA.

20250902 072804	180	23	825	4	5	54003000	110

[mbo] 94: num.trees=180; max.depth=23; min.node.size=825; mtry=4 : y = 5.4e+07 : 162.7 secs : infill_ei

Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 41 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 6 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 40%. Estimated remaining time: 3 minutes, 5 seconds.
Growing trees.. Progress: 50%. Estimated remaining time: 2 minutes, 34 seconds.
Growing trees.. Progress: 60%. Estimated remaining time: 2 minutes, 3 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 1 minute, 32 seconds.
Growing trees.. Progress: 81%. Estimated remaining time: 1 minute, 0 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 29 seconds.
Growing trees.. Progress: 100%. Estimated remaining time: 0 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 49 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 18 seconds.
Growing trees.. Progress: 30%. Estimated remaining time: 3 minutes, 44 seconds.
Growing trees.. Progress: 39%. Estimated remaining time: 3 minutes, 15 seconds.
Growing trees.. Progress: 49%. Estimated remaining time: 2 minutes, 45 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 2 minutes, 14 seconds.
Growing trees.. Progress: 68%. Estimated remaining time: 1 minute, 44 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 42 seconds.
Growing trees.. Progress: 97%. Estimated remaining time: 10 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 49 seconds.
Growing trees.. Progress: 19%. Estimated remaining time: 4 minutes, 18 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 3 minutes, 55 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 3 minutes, 24 seconds.
Growing trees.. Progress: 47%. Estimated remaining time: 2 minutes, 53 seconds.
Growing trees.. Progress: 57%. Estimated remaining time: 2 minutes, 22 seconds.
Growing trees.. Progress: 66%. Estimated remaining time: 1 minute, 52 seconds.
Growing trees.. Progress: 76%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 86%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 95%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 9%. Estimated remaining time: 5 minutes, 16 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 4 minutes, 40 seconds.
Growing trees.. Progress: 28%. Estimated remaining time: 4 minutes, 9 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 3 minutes, 36 seconds.
Growing trees.. Progress: 46%. Estimated remaining time: 3 minutes, 2 seconds.
Growing trees.. Progress: 56%. Estimated remaining time: 2 minutes, 29 seconds.
Growing trees.. Progress: 65%. Estimated remaining time: 1 minute, 58 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 1 minute, 26 seconds.
Growing trees.. Progress: 84%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 94%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 10%. Estimated remaining time: 4 minutes, 58 seconds.
Growing trees.. Progress: 20%. Estimated remaining time: 4 minutes, 22 seconds.
Growing trees.. Progress: 29%. Estimated remaining time: 3 minutes, 52 seconds.
Growing trees.. Progress: 38%. Estimated remaining time: 3 minutes, 21 seconds.
Growing trees.. Progress: 48%. Estimated remaining time: 2 minutes, 48 seconds.
Growing trees.. Progress: 58%. Estimated remaining time: 2 minutes, 17 seconds.
Growing trees.. Progress: 67%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 1 minute, 14 seconds.
Growing trees.. Progress: 87%. Estimated remaining time: 43 seconds.
Growing trees.. Progress: 96%. Estimated remaining time: 12 seconds.
20250902 075617	403	15	354	26	5	55044000	111

[mbo] 95: num.trees=403; max.depth=15; min.node.size=354; mtry=26 : y = 5.5e+07 : 1692.0 secs : infill_ei

Saved the current state after iteration 96 in the file HT450.RDATA.

20250902 075824	77	24	998	8	5	53964000	112

[mbo] 96: num.trees=77; max.depth=24; min.node.size=998; mtry=8 : y = 5.4e+07 : 121.5 secs : infill_ei

Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 19 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 1 minute, 50 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 1 minute, 16 seconds.
Growing trees.. Progress: 74%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 1 minute, 50 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 1 minute, 20 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 1 minute, 21 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 49 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 17 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 15 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 1 minute, 48 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 1 minute, 17 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 46 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 16 seconds.
20250902 081330	182	17	427	29	5	54423000	113

[mbo] 97: num.trees=182; max.depth=17; min.node.size=427; mtry=29 : y = 5.44e+07 : 905.0 secs : infill_ei

Saved the current state after iteration 98 in the file HT450.RDATA.

Growing trees.. Progress: 78%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 79%. Estimated remaining time: 8 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 77%. Estimated remaining time: 9 seconds.
Growing trees.. Progress: 78%. Estimated remaining time: 8 seconds.
20250902 081756	428	16	155	2	5	53751000	114

[mbo] 98: num.trees=428; max.depth=16; min.node.size=155; mtry=2 : y = 5.38e+07 : 260.4 secs : infill_ei

Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 72%. Estimated remaining time: 48 seconds.
Growing trees.. Progress: 90%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 1 minute, 18 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 92%. Estimated remaining time: 13 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 28 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 20 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 1 minute, 49 seconds.
Growing trees.. Progress: 54%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 16 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 24 seconds.
Growing trees.. Progress: 36%. Estimated remaining time: 1 minute, 51 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 1 minute, 19 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 47 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 15 seconds.
20250902 083302	255	18	1000	21	5	55011000	115

[mbo] 99: num.trees=255; max.depth=18; min.node.size=1000; mtry=21 : y = 5.5e+07 : 904.7 secs : infill_ei

Saved the current state after iteration 100 in the file HT450.RDATA.

Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 17 seconds.
Growing trees.. Progress: 37%. Estimated remaining time: 1 minute, 46 seconds.
Growing trees.. Progress: 55%. Estimated remaining time: 1 minute, 15 seconds.
Growing trees.. Progress: 73%. Estimated remaining time: 45 seconds.
Growing trees.. Progress: 91%. Estimated remaining time: 14 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 1 minute, 55 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 89%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 23 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 1 minute, 54 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 70%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 21 seconds.
Growing trees.. Progress: 18%. Estimated remaining time: 2 minutes, 25 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 1 minute, 53 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 1 minute, 22 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 51 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 20 seconds.
Growing trees.. Progress: 17%. Estimated remaining time: 2 minutes, 27 seconds.
Growing trees.. Progress: 35%. Estimated remaining time: 1 minute, 54 seconds.
Growing trees.. Progress: 53%. Estimated remaining time: 1 minute, 23 seconds.
Growing trees.. Progress: 71%. Estimated remaining time: 52 seconds.
Growing trees.. Progress: 88%. Estimated remaining time: 20 seconds.
20250902 084844	472	14	924	13	5	55404000	116

[mbo] 100: num.trees=472; max.depth=14; min.node.size=924; mtry=13 : y = 5.54e+07 : 936.9 secs : infill_ei

Saved the final state in the file HT450.RDATA

Saved the final state in the file HT450.RDATA

In [21]:
# analizo la salida de la bayesiana

tb_bayesiana <- fread(klog)
setorder( tb_bayesiana, -ganancia)
tb_bayesiana

    fecha           num.trees max.depth min.node.size mtry xval_folds ganancia
1   20250901 072054 177       17        1000          11   5          57267000
2   20250901 121941 394       17        1000          11   5          56232000
3   20250831 195936 271       12         176          25   5          56157000
4   20250901 110731 477       17         126          11   5          56127000
5   20250901 080959 488       16        1000          11   5          55938000
6   20250901 165616 321       13         496          32   5          55908000
7   20250901 140938  84       30        1000          11   5          55866000
8   20250901 032813 500       14         534          50   5          55842000
9   20250901 011059 500       30        1000          14   5          55752000
10  20250901 181812 494       13        1000          49   5          55710000
11  20250831 223854 500       12         586          37   5          55647000
12  20250901 125819 123       12        1000          11   5          55617000
13  20250901 132837 490       10         354          34   5          55605000
14  20250901 125443 500       18         386          23   5          55575000
15  20250831 234320 324       12         630          24   5          55539000
16  20250901 120551 500       14         598          45   5          55530000
17  20250901 205747 274       10         381          25   5          55512000
18  20250901 155730 386       10           1          22   5          55464000
19  20250831 194430 495       15         512          18   5          55458000
20  20250831 203645 315       11         840          11   5          55446000
21  20250901 083608 222       17        1000          15   5          55440000
22  20250901 070041 317       30         790          13   5          55425000
23  20250902 084844 472       14         924          13   5          55404000
24  20250901 002119 209       19         885          12   5          55398000
25  20250901 160719 500       20         242           5   5          55347000
26  20250902 055533 500       26         977          44   5          55326000
27  20250902 042529 310       19        1000          32   5          55311000
28  20250831 210609 189       17         239           5   5          55266000
29  20250901 014426 500       11         221          27   5          55260000
30  20250901 015355 272       16         513          12   5          55242000
⋮   ⋮               ⋮         ⋮         ⋮             ⋮    ⋮          ⋮
87  20250831 235304 206        6           1          50   5          53640000
88  20250901 082640 309        7        1000          50   5          53604000
89  20250901 161311  20       13         475          50   5          53586000
90  20250901 100158 304       20         951           2   5          53532000
91  20250831 211404 101        8         980          47   5          53469000
92  20250831 215414  69       14        1000          16   5          53310000
93  20250901 120652  22        7           6          26   5          53304000
94  20250831 215935 500       25        1000           2   5          53286000
95  20250901 004858 500        7         989          41   5          53079000
96  20250831 235737 500       13         226           2   5          53040000
97  20250902 072515 465       19         999           2   5          53028000
98  20250901 144747 500       30           1           6   5          52908000
99  20250902 000414 281       18           1          11   5          52707000
100 20250831 202913 219       21         734          42   5          52635000
101 20250831 204323 326        4         404          38   5          52575000
102 20250901 101601 266       30         893           2   5          52572000
103 20250901 085335 500       25          32          10   5          52512000
104 20250901 004953  20       24         550          11   5          52449000
105 20250831 200042  43        6         777          21   5          52398000
106 20250901 140533 494       30         115          22   5          52353000
107 20250901 052928 145       19         498           2   5          52347000
108 20250901 221718  20       10         423          33   5          52314000
109 20250901 074606  20       17        1000          17   5          51777000
110 20250901 161031  29       30        1000          31   5          51735000
111 20250831 232536 482       17           1          31   5          51681000
112 20250831 192023 361       24          90          49   5          51114000
113 20250831 210236 137       27          56          40   5          47535000
114 20250901 231831  20       30          79           5   5          47085000
115 20250901 172205 500        1         582          48   5          43353000
116 20250831 210659 447        1         300           9   5          29814000
    iteracion
1    43
2    65
3     6
4    62
5    48
6    79
7    70
8    35
9    29
10   82
11   19
12   67
13   68
14   66
15   21
16   63
17   86
18   74
19    5
20    9
21   50
22   41
23  116
24   25
25   75
26  106
27  103
28   12
29   31
30   32
⋮   ⋮
87   22
88   49
89   77
90   55
91   15
92   17
93   64
94   18
95   27
96   23
97  109
98   72
99   96
100   8
101  10
102  58
103  51
104  28
105   7
106  69
107  38
108  90
109  45
110  76
111  20
112   4
113  11
114  92
115  81
116  13

In [22]:
# mejores parametros

print( tb_bayesiana[1] )

             fecha num.trees max.depth min.node.size  mtry xval_folds ganancia
            <char>     <int>     <int>         <int> <int>      <int>    <int>
1: 20250901 072054       177        17          1000    11          5 57267000
   iteracion
       <int>
1:        43

In [23]:
format(Sys.time(), "%a %b %d %X %Y")

[1] "Tue Sep 02 08:49:01 2025"



---